<Project>
  <PropertyGroup>
    <NScriptRoot>$(MSBuildThisFileDirectory)</NScriptRoot>
    <Dependencies>$(NScriptRoot)/Dependencies</Dependencies>
    <NScriptToolsetDir>$(NScriptRoot)/NScriptToolSet</NScriptToolsetDir>
    <CompilerSources>$(NScriptRoot)/Sources/Compiler</CompilerSources>
    <CompilerTestSources>$(NScriptRoot)/Test/Compiler</CompilerTestSources>
    <SolutionDir>$(NScriptRoot)</SolutionDir>
    <TestOutputDir>$(NScriptRoot)/Test/TestBin</TestOutputDir>
    <CompilerNetFramework>net8.0</CompilerNetFramework>
    <NScriptIsWindows>$([MSBuild]::IsOSPlatform('Windows'))</NScriptIsWindows>
    <NScriptCompilerToolName Condition="'$(NScriptCompilerToolName)' == '' and '$(NScriptIsWindows)' == 'True'">csc.exe</NScriptCompilerToolName>
    <NScriptCompilerToolName Condition="'$(NScriptCompilerToolName)' == '' and '$(NScriptIsWindows)' != 'True'">csc</NScriptCompilerToolName>
    <NScriptEmitterToolFileName Condition="'$(NScriptEmitterToolFileName)' == '' and '$(NScriptIsWindows)' == 'True'">nscript.exe</NScriptEmitterToolFileName>
    <NScriptEmitterToolFileName Condition="'$(NScriptEmitterToolFileName)' == '' and '$(NScriptIsWindows)' != 'True'">nscript</NScriptEmitterToolFileName>
    <NScriptToolsetBinDir Condition="'$(NScriptToolsetBinDir)' == '' and '$(NScriptIsWindows)' == 'True'">$(NScriptToolsetDir)\bin\$(Configuration)\$(CompilerNetFramework)\</NScriptToolsetBinDir>
    <NScriptToolsetBinDir Condition="'$(NScriptToolsetBinDir)' == '' and '$(NScriptIsWindows)' != 'True'">$(NScriptToolsetDir)/bin/$(Configuration)/$(CompilerNetFramework)/</NScriptToolsetBinDir>
    <NScriptToolsetDebugBinDir Condition="'$(NScriptToolsetDebugBinDir)' == '' and '$(NScriptIsWindows)' == 'True'">$(NScriptToolsetDir)\bin\Debug\$(CompilerNetFramework)\</NScriptToolsetDebugBinDir>
    <NScriptToolsetDebugBinDir Condition="'$(NScriptToolsetDebugBinDir)' == '' and '$(NScriptIsWindows)' != 'True'">$(NScriptToolsetDir)/bin/Debug/$(CompilerNetFramework)/</NScriptToolsetDebugBinDir>
  </PropertyGroup>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministric>true</Deterministric>
    <!--Set this to true to generate packages-->
    <GenerateNScriptPackages>true</GenerateNScriptPackages>
    <!--Update package version here-->
    <NScriptPackageVersion>1.1.0</NScriptPackageVersion>
	</PropertyGroup>
</Project>
