using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Cs2JsC.CLR.Decompiler
{
    public enum FlowType
    {
        Switch,
        Branch,
        ConditionalBranch,
        MethodCall,
        Next,
        Throw,
        Return,
        Leave,
        Unsuported,
    }

    public enum StackPopCode
    {
        Pop0,
        Pop1,
        Pop2,
        Pop3,
        PopVar,
        PopAll
    }

    public enum StackPushCode
    {
        Push0,
        Push1,
        Push2,
        PushVar
    }

    public enum OpArgumentType
    {
        None,
        ArgumentId,
        LocalVariableId,
        Field,
        Method,
        BranchTarget,
        SwitchTargets,
        Constant,
        ConstantDouble,
        ConstantString,
        ObjectType,
        Token,
    }

    public enum ElementAccessType
    {
        None,
        GetStaticProperty,
        GetProperty,
        GetStaticField,
        GetField,
        GetArray,
        GetReferenceArgument,
        GetArgument,
        GetLocal,
        SetStaticProperty,
        SetProperty,
        SetStaticField,
        SetField,
        SetArray,
        SetReferenceArgument,
        SetArgument,
        SetLocal,
    }

    public enum OpCode : ushort
    {
        Nop = 0x00,
        Break = 0x01,
        LoadArgument_0 = 0x02,
        LoadArgument_1 = 0x03,
        LoadArgument_2 = 0x04,
        LoadArgument_3 = 0x05,
        LoadLocal_0 = 0x06,
        LoadLocal_1 = 0x07,
        LoadLocal_2 = 0x08,
        LoadLocal_3 = 0x09,
        StoreLocal_0 = 0x0A,
        StoreLocal_1 = 0x0B,
        StoreLocal_2 = 0x0C,
        StoreLocal_3 = 0x0D,
        LoadArgument_s = 0x0E,
        LoadArgumentAddress_s = 0x0F,
        StoreArgument_s = 0x10,
        LoadLocal_s = 0x11,
        LoadLocalAddress_s = 0x12,
        StoreLocal_s = 0x13,
        LoadNull = 0x14,
        LoadConstantInt32_m1 = 0x15,
        LoadConstantInt32_0 = 0x16,
        LoadConstantInt32_1 = 0x17,
        LoadConstantInt32_2 = 0x18,
        LoadConstantInt32_3 = 0x19,
        LoadConstantInt32_4 = 0x1A,
        LoadConstantInt32_5 = 0x1B,
        LoadConstantInt32_6 = 0x1C,
        LoadConstantInt32_7 = 0x1D,
        LoadConstantInt32_8 = 0x1E,
        LoadConstantInt32_s = 0x1F,
        LoadConstantInt32 = 0x20,
        LoadConstantInt64 = 0x21,
        LoadConstantSingle = 0x22,
        LoadConstantDouble = 0x23,
        Dup = 0x25,
        Pop = 0x26,
        Jmp = 0x27,
        Call = 0x28,
        CallIndirect = 0x29,
        Return = 0x2A,
        Branch_s = 0x2B,
        BranchFalse_s = 0x2C,
        BranchTrue_s = 0x2D,
        BranchEq_s = 0x2E,
        BranchGe_s = 0x2F,
        BranchGt_s = 0x30,
        BranchLe_s = 0x31,
        BranchLt_s = 0x32,
        BranchUNe_s = 0x33,
        BranchUGe_s = 0x34,
        BranchUGt_s = 0x35,
        BranchULe_s = 0x36,
        BranchULt_s = 0x37,
        Branch = 0x38,
        BranchFalse = 0x39,
        BranchTrue = 0x3A,
        BranchEq = 0x3B,
        BranchGe = 0x3C,
        BranchGt = 0x3D,
        BranchLe = 0x3E,
        BranchLt = 0x3F,
        BranchUNe = 0x40,
        BranchUGe = 0x41,
        BranchUGt = 0x42,
        BranchULe = 0x43,
        BranchULt = 0x44,
        Switch = 0x45,
        LoadIndirectInt8 = 0x46,
        LoadIndirectUInt8 = 0x47,
        LoadIndirectInt16 = 0x48,
        LoadIndirectUInt16 = 0x49,
        LoadIndirectInt32 = 0x4A,
        LoadIndirectUInt32 = 0x4B,
        LoadIndirectInt64 = 0x4C,
        LoadIndirectIntPtr = 0x4D,
        LoadIndirectSingle = 0x4E,
        LoadIndirectDouble = 0x4F,
        LoadIndirect_ref = 0x50,
        StoreIndirect_ref = 0x51,
        StoreIndirectInt8 = 0x52,
        StoreIndirectInt16 = 0x53,
        StoreIndirectInt32 = 0x54,
        StoreIndirectInt64 = 0x55,
        StoreIndirectSingle = 0x56,
        StoreIndirectDouble = 0x57,
        Add = 0x58,
        Sub = 0x59,
        Mul = 0x5A,
        Div = 0x5B,
        Div_un = 0x5C,
        Rem = 0x5D,
        Rem_un = 0x5E,
        And = 0x5F,
        Or = 0x60,
        Xor = 0x61,
        Shl = 0x62,
        Shr = 0x63,
        Shr_un = 0x64,
        Neg = 0x65,
        Not = 0x66,
        ConvertToInt8 = 0x67,
        ConvertToInt16 = 0x68,
        ConvertToInt32 = 0x69,
        ConvertToInt64 = 0x6A,
        ConvertToSingle = 0x6B,
        ConvertToDouble = 0x6C,
        ConvertToUInt32 = 0x6D,
        ConvertToUInt64 = 0x6E,
        CallVirtual = 0x6F,
        CopyObject = 0x70,
        LoadObject = 0x71,
        LoadString = 0x72,
        Newobj = 0x73,
        Castclass = 0x74,
        Isinst = 0x75,
        Conv_r_un = 0x76,
        Unbox = 0x79,
        Throw = 0x7A,
        LoadField = 0x7B,
        LoadFieldAddress = 0x7C,
        StoreField = 0x7D,
        LoadStaticField = 0x7E,
        LoadStaticFieldAddress = 0x7F,
        StoreStaticField = 0x80,
        StoreObject = 0x81,
        ConvertUnsignedOverflowToInt8 = 0x82,
        ConvertUnsignedOverflowToInt16 = 0x83,
        ConvertUnsignedOverflowToInt32 = 0x84,
        ConvertUnsignedOverflowToInt64 = 0x85,
        ConvertUnsignedOverflowToUInt8 = 0x86,
        ConvertUnsignedOverflowToUInt16 = 0x87,
        ConvertUnsignedOverflowToUInt32 = 0x88,
        ConvertUnsignedOverflowToUInt64 = 0x89,
        ConvertUnsignedOverflowToIntPtr = 0x8A,
        ConvertUnsignedOverflowToUIntPtr = 0x8B,
        Box = 0x8C,
        Newarr = 0x8D,
        LoadLength = 0x8E,
        LoadElementAddress = 0x8F,
        LoadElementInt8 = 0x90,
        LoadElementUInt8 = 0x91,
        LoadElementInt16 = 0x92,
        LoadElementUInt16 = 0x93,
        LoadElementInt32 = 0x94,
        LoadElementUInt32 = 0x95,
        LoadElementInt64 = 0x96,
        LoadElementIntPtr = 0x97,
        LoadElementSingle = 0x98,
        LoadElementDouble = 0x99,
        LoadElement_ref = 0x9A,
        StoreElementIntPtr = 0x9B,
        StoreElementInt8 = 0x9C,
        StoreElementInt16 = 0x9D,
        StoreElementInt32 = 0x9E,
        StoreElementInt64 = 0x9F,
        StoreElementSingle = 0xA0,
        StoreElementDouble = 0xA1,
        StoreElement_ref = 0xA2,
        LoadElement = 0xA3,
        StoreElement = 0xA4,
        Unbox_any = 0xA5,
        ConvertOverflowToInt8 = 0xB3,
        ConvertOverflowToUInt8 = 0xB4,
        ConvertOverflowToInt16 = 0xB5,
        ConvertOverflowToUInt16 = 0xB6,
        ConvertOverflowToInt32 = 0xB7,
        ConvertOverflowToUInt32 = 0xB8,
        ConvertOverflowToInt64 = 0xB9,
        ConvertOverflowToUInt64 = 0xBA,
        Refanyval = 0xC2,
        Ckfinite = 0xC3,
        Mkrefany = 0xC6,
        Ldtoken = 0xD0,
        ConvertToUInt16 = 0xD1,
        ConvertToUInt8 = 0xD2,
        ConvertToIntPtr = 0xD3,
        ConvertOverflowToIntPtr = 0xD4,
        ConvertOverflowToUIntPtr = 0xD5,
        Add_ovf = 0xD6,
        Add_ovf_un = 0xD7,
        Mul_ovf = 0xD8,
        Mul_ovf_un = 0xD9,
        Sub_ovf = 0xDA,
        Sub_ovf_un = 0xDB,
        Endfinally = 0xDC,
        Leave = 0xDD,
        Leave_s = 0xDE,
        StoreIndirectIntPtr = 0xDF,
        Conv_u = 0xE0,
        Prefix7 = 0xF8,
        Prefix6 = 0xF9,
        Prefix5 = 0xFA,
        Prefix4 = 0xFB,
        Prefix3 = 0xFC,
        Prefix2 = 0xFD,
        Prefix1 = 0xFE,
        Prefixref = 0xFF,
        Arglist = 0xFE00,
        CompareEq = 0xFE01,
        CompareGt = 0xFE02,
        CompareUGt = 0xFE03,
        CompareLt = 0xFE04,
        CompareULt = 0xFE05,
        LoadFunction = 0xFE06,
        LoadVirtualFunction = 0xFE07,
        LoadArgument = 0xFE09,
        LoadArgumentAddress = 0xFE0A,
        StoreArgument = 0xFE0B,
        LoadLocal = 0xFE0C,
        LoadLocalAddress = 0xFE0D,
        StoreLocal = 0xFE0E,
        Localloc = 0xFE0F,
        Endfilter = 0xFE11,
        Unaligned = 0xFE12,
        Volatile = 0xFE13,
        Tailcall = 0xFE14,
        Initobj = 0xFE15,
        Constrained = 0xFE16,
        Cpblk = 0xFE17,
        Initblk = 0xFE18,
        No = 0xFE10,
        Rethrow = 0xFE1A,
        Sizeof = 0xFE1C,
        Refanytype = 0xFE1D,
        Readonly = 0xFE1E,
        DupCopy,
        CatchEntry,
        LoadDefaultValue,
    }
}
