<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(CompilerNetFramework)</TargetFramework>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.36" />
    <PackageReference Include="System.Collections.Immutable" Version="10.0.1" />
    <PackageReference Include="System.Reflection.Metadata" Version="10.0.1" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="2.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CodeAnalysis">
      <HintPath>$(Dependencies)\Roslyn\Microsoft.CodeAnalysis.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.CSharp">
      <HintPath>$(Dependencies)\Roslyn\Microsoft.CodeAnalysis.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Private">
      <HintPath>$(Dependencies)\Mono.Cecil.Private.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NScript.CLR\NScript.CLR.csproj" />
    <ProjectReference Include="..\NScript.Converter\NScript.Converter.csproj" />
    <ProjectReference Include="..\NScript.JST\NScript.JS.AST.csproj" />
    <ProjectReference Include="..\NScript.Utils\NScript.Utils.csproj" />
  </ItemGroup>
</Project>
