<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.36" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NScript.CLR\NScript.CLR.csproj" />
    <ProjectReference Include="..\NScript.Converter\NScript.Converter.csproj" />
    <ProjectReference Include="..\NScript.JST\NScript.JS.AST.csproj" />
    <ProjectReference Include="..\NScript.Utils\NScript.Utils.csproj" />
  </ItemGroup>
</Project>
