<Project>
    <Import
        Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
    <PropertyGroup>
        <CscToolPath>
            $(MSBuildThisFileDirectory)../../NScriptToolSet/bin/Debug/$(CompilerNetFramework)/</CscToolPath>
        <CscToolExe>csc.exe</CscToolExe>
        <NScriptExe>
            $(MSBuildThisFileDirectory)../../NScriptToolSet/bin/Debug/$(CompilerNetFramework)/nscript.exe</NScriptExe>
        <LangVersion>8.0</LangVersion>
    </PropertyGroup>
</Project>