<Project>
  <Import Project="../../../Sources/Compiler/NScript.Sdk/Sdk/Sdk.props" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>$(CompilerNetFramework)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Sunlight.Framework.Data.Test</RootNamespace>
    <AssemblyName>Sunlight.Framework.Data.Test</AssemblyName>
    <GenerateJs>True</GenerateJs>
    <PluginConfig>PluginConfig.xml</PluginConfig>
    <JsOutputPath>../TestWebApplication/GeneratedScripts</JsOutputPath>
    <CscToolPath>$(NScriptToolsetBinDir)</CscToolPath>
    <CscToolExe>$(NScriptCompilerToolName)</CscToolExe>
    <NScriptExe>$(NScriptToolsetBinDir)$(NScriptEmitterToolFileName)</NScriptExe>
  </PropertyGroup>

  <ItemGroup>
    <None Include="PluginConfig.xml">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Sources\Framework\mscorlib\NScript.MsCorlib.csproj" />
    <ProjectReference Include="..\..\..\Sources\Framework\System.Web.Html\System.Web.Html.csproj" />
    <ProjectReference Include="..\..\..\Sources\Framework\System.Web\System.Web.csproj" />
    <ProjectReference Include="..\..\..\Sources\Framework\SunlightUnit\SunlightUnit.csproj" />
    <ProjectReference Include="..\..\..\Sources\Framework\Sunlight.Framework\Sunlight.Framework.csproj" />
    <ProjectReference Include="..\..\..\Sources\Framework\Sunlight.Framework.UI\Sunlight.Framework.UI.csproj" />
    <ProjectReference Include="..\..\..\Sources\Framework\Sunlight.Framework.Data\Sunlight.Framework.Data.csproj" />
  </ItemGroup>

  <Import Project="../../../Sources/Compiler/NScript.Sdk/Sdk/Sdk.targets" />
</Project>
