using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NScript.PELoader;

namespace NScript.Lib.AsmDeasm.Ops
{
    internal static class OpCodeHelper
    {
        public static StackPopCode GetPops(OpCode opCode)
        {
            switch (opCode)
            {
                case OpCode.Nop:
                case OpCode.Break:
                case OpCode.LoadArgument_0:
                case OpCode.LoadArgument_1:
                case OpCode.LoadArgument_2:
                case OpCode.LoadArgument_3:
                case OpCode.LoadLocal_0:
                case OpCode.LoadLocal_1:
                case OpCode.LoadLocal_2:
                case OpCode.LoadLocal_3:
                case OpCode.LoadArgument_s:
                case OpCode.LoadArgumentAddress_s:
                case OpCode.LoadLocal_s:
                case OpCode.LoadLocalAddress_s:
                case OpCode.LoadNull:
                case OpCode.LoadConstantInt32_m1:
                case OpCode.LoadConstantInt32_0:
                case OpCode.LoadConstantInt32_1:
                case OpCode.LoadConstantInt32_2:
                case OpCode.LoadConstantInt32_3:
                case OpCode.LoadConstantInt32_4:
                case OpCode.LoadConstantInt32_5:
                case OpCode.LoadConstantInt32_6:
                case OpCode.LoadConstantInt32_7:
                case OpCode.LoadConstantInt32_8:
                case OpCode.LoadConstantInt32_s:
                case OpCode.LoadConstantInt32:
                case OpCode.LoadConstantInt64:
                case OpCode.LoadConstantSingle:
                case OpCode.LoadConstantDouble:
                case OpCode.Jmp:
                case OpCode.Branch_s:
                case OpCode.BranchFalse_s:
                case OpCode.BranchTrue_s:
                case OpCode.BranchEq_s:
                case OpCode.BranchGe_s:
                case OpCode.BranchGt_s:
                case OpCode.BranchLe_s:
                case OpCode.BranchLt_s:
                case OpCode.BranchUNe_s:
                case OpCode.BranchUGe_s:
                case OpCode.BranchUGt_s:
                case OpCode.BranchULe_s:
                case OpCode.BranchULt_s:
                case OpCode.Branch:
                case OpCode.BranchFalse:
                case OpCode.BranchTrue:
                case OpCode.BranchEq:
                case OpCode.BranchGe:
                case OpCode.BranchGt:
                case OpCode.BranchLe:
                case OpCode.BranchLt:
                case OpCode.BranchUNe:
                case OpCode.BranchUGe:
                case OpCode.BranchUGt:
                case OpCode.BranchULe:
                case OpCode.BranchULt:
                case OpCode.Switch:
                case OpCode.LoadString:
                case OpCode.Arglist:
                case OpCode.LoadArgument:
                case OpCode.LoadArgumentAddress:
                case OpCode.LoadLocal:
                case OpCode.LoadLocalAddress:
                case OpCode.Endfinally:
                case OpCode.Rethrow:
                case OpCode.Ldtoken:
                case OpCode.LoadFunction:
                    return StackPopCode.Pop0;
                case OpCode.StoreLocal_0:
                case OpCode.StoreLocal_1:
                case OpCode.StoreLocal_2:
                case OpCode.StoreLocal_3:
                case OpCode.StoreArgument_s:
                case OpCode.StoreLocal_s:
                case OpCode.Dup:
                case OpCode.Pop:
                case OpCode.LoadIndirectInt8:
                case OpCode.LoadIndirectUInt8:
                case OpCode.LoadIndirectInt16:
                case OpCode.LoadIndirectUInt16:
                case OpCode.LoadIndirectInt32:
                case OpCode.LoadIndirectUInt32:
                case OpCode.LoadIndirectInt64:
                case OpCode.LoadIndirectIntPtr:
                case OpCode.LoadIndirectSingle:
                case OpCode.LoadIndirectDouble:
                case OpCode.LoadIndirect_ref:
                case OpCode.Neg:
                case OpCode.Not:
                case OpCode.ConvertToInt8:
                case OpCode.ConvertToInt16:
                case OpCode.ConvertToInt32:
                case OpCode.ConvertToInt64:
                case OpCode.ConvertToSingle:
                case OpCode.ConvertToDouble:
                case OpCode.ConvertToUInt32:
                case OpCode.ConvertToUInt64:
                case OpCode.LoadObject:
                case OpCode.Castclass:
                case OpCode.Isinst:
                case OpCode.Box:
                case OpCode.Unbox:
                case OpCode.Throw:
                case OpCode.LoadField:
                case OpCode.LoadFieldAddress:
                case OpCode.LoadStaticField:
                case OpCode.LoadStaticFieldAddress:
                case OpCode.ConvertUnsignedOverflowToInt8:
                case OpCode.ConvertUnsignedOverflowToInt16:
                case OpCode.ConvertUnsignedOverflowToInt32:
                case OpCode.ConvertUnsignedOverflowToInt64:
                case OpCode.ConvertUnsignedOverflowToUInt8:
                case OpCode.ConvertUnsignedOverflowToUInt16:
                case OpCode.ConvertUnsignedOverflowToUInt32:
                case OpCode.ConvertUnsignedOverflowToUInt64:
                case OpCode.ConvertUnsignedOverflowToIntPtr:
                case OpCode.ConvertUnsignedOverflowToUIntPtr:
                case OpCode.Newarr:
                case OpCode.LoadLength:
                case OpCode.Unbox_any:
                case OpCode.Refanyval:
                case OpCode.Ckfinite:
                case OpCode.Mkrefany:
                case OpCode.ConvertToUInt16:
                case OpCode.ConvertToUInt8:
                case OpCode.ConvertToIntPtr:
                case OpCode.ConvertOverflowToIntPtr:
                case OpCode.ConvertOverflowToUIntPtr:
                case OpCode.Conv_u:
                case OpCode.LoadVirtualFunction:
                case OpCode.StoreArgument:
                case OpCode.StoreLocal:
                case OpCode.Endfilter:
                case OpCode.Localloc:
                case OpCode.Sizeof:
                case OpCode.Refanytype:
                    return StackPopCode.Pop1;
                case OpCode.StoreIndirect_ref:
                case OpCode.StoreIndirectInt8:
                case OpCode.StoreIndirectInt16:
                case OpCode.StoreIndirectInt32:
                case OpCode.StoreIndirectInt64:
                case OpCode.StoreIndirectSingle:
                case OpCode.StoreIndirectDouble:
                case OpCode.Add:
                case OpCode.Sub:
                case OpCode.Mul:
                case OpCode.Div:
                case OpCode.Div_un:
                case OpCode.Rem:
                case OpCode.Rem_un:
                case OpCode.And:
                case OpCode.Or:
                case OpCode.Xor:
                case OpCode.Shl:
                case OpCode.Shr:
                case OpCode.Shr_un:
                case OpCode.CopyObject:
                case OpCode.StoreField:
                case OpCode.StoreStaticField:
                case OpCode.StoreObject:
                case OpCode.LoadElementAddress:
                case OpCode.LoadElementInt8:
                case OpCode.LoadElementUInt8:
                case OpCode.LoadElementInt16:
                case OpCode.LoadElementUInt16:
                case OpCode.LoadElementInt32:
                case OpCode.LoadElementUInt32:
                case OpCode.LoadElementInt64:
                case OpCode.LoadElementIntPtr:
                case OpCode.LoadElementSingle:
                case OpCode.LoadElementDouble:
                case OpCode.LoadElement_ref:
                case OpCode.LoadElement:
                case OpCode.Add_ovf:
                case OpCode.Add_ovf_un:
                case OpCode.Mul_ovf:
                case OpCode.Mul_ovf_un:
                case OpCode.Sub_ovf:
                case OpCode.Sub_ovf_un:
                case OpCode.StoreIndirectIntPtr:
                case OpCode.CompareEq:
                case OpCode.CompareGt:
                case OpCode.CompareUGt:
                case OpCode.CompareLt:
                case OpCode.CompareULt:
                case OpCode.Initobj:
                    return StackPopCode.Pop2;
                case OpCode.StoreElementIntPtr:
                case OpCode.StoreElementInt8:
                case OpCode.StoreElementInt16:
                case OpCode.StoreElementInt32:
                case OpCode.StoreElementInt64:
                case OpCode.StoreElementSingle:
                case OpCode.StoreElementDouble:
                case OpCode.StoreElement_ref:
                case OpCode.StoreElement:
                case OpCode.Cpblk:
                case OpCode.Initblk:
                    return StackPopCode.Pop3;
                case OpCode.Call:
                case OpCode.CallIndirect:
                case OpCode.CallVirtual:
                case OpCode.Newobj:
                case OpCode.Tailcall:
                    return StackPopCode.PopVar;
                case OpCode.Return:
                case OpCode.Leave:
                case OpCode.Leave_s:
                    return StackPopCode.PopAll;
                case OpCode.Conv_r_un:
                case OpCode.Prefix7:
                case OpCode.Prefix6:
                case OpCode.Prefix5:
                case OpCode.Prefix4:
                case OpCode.Prefix3:
                case OpCode.Prefix2:
                case OpCode.Prefix1:
                case OpCode.Prefixref:
                case OpCode.Unaligned:
                case OpCode.Volatile:
                case OpCode.Constrained:
                case OpCode.Readonly:
                default:
                    throw new NotSupportedException();
            }
        }

        public static StackPushCode GetPushes(OpCode opCode)
        {
            switch (opCode)
            {
                case OpCode.Nop:
                case OpCode.Break:
                    return StackPushCode.Push0;
                case OpCode.LoadArgument_0:
                case OpCode.LoadArgument_1:
                case OpCode.LoadArgument_2:
                case OpCode.LoadArgument_3:
                case OpCode.LoadLocal_0:
                case OpCode.LoadLocal_1:
                case OpCode.LoadLocal_2:
                case OpCode.LoadLocal_3:
                    return StackPushCode.Push1;
                case OpCode.StoreLocal_0:
                case OpCode.StoreLocal_1:
                case OpCode.StoreLocal_2:
                case OpCode.StoreLocal_3:
                    return StackPushCode.Push0;
                case OpCode.LoadArgument_s:
                case OpCode.LoadArgumentAddress_s:
                    return StackPushCode.Push1;
                case OpCode.StoreArgument_s:
                    return StackPushCode.Push0;
                case OpCode.LoadLocal_s:
                case OpCode.LoadLocalAddress_s:
                    return StackPushCode.Push1;
                case OpCode.StoreLocal_s:
                    return StackPushCode.Push0;
                case OpCode.LoadNull:
                case OpCode.LoadConstantInt32_m1:
                case OpCode.LoadConstantInt32_0:
                case OpCode.LoadConstantInt32_1:
                case OpCode.LoadConstantInt32_2:
                case OpCode.LoadConstantInt32_3:
                case OpCode.LoadConstantInt32_4:
                case OpCode.LoadConstantInt32_5:
                case OpCode.LoadConstantInt32_6:
                case OpCode.LoadConstantInt32_7:
                case OpCode.LoadConstantInt32_8:
                case OpCode.LoadConstantInt32_s:
                case OpCode.LoadConstantInt32:
                case OpCode.LoadConstantInt64:
                case OpCode.LoadConstantSingle:
                case OpCode.LoadConstantDouble:
                    return StackPushCode.Push1;
                case OpCode.Dup:
                    return StackPushCode.Push2;
                case OpCode.Pop:
                case OpCode.Jmp:
                    return StackPushCode.Push0;
                case OpCode.Call:
                case OpCode.CallIndirect:
                    return StackPushCode.PushVar;
                case OpCode.Return:
                    return StackPushCode.Push0;
                case OpCode.Branch_s:
                case OpCode.BranchFalse_s:
                case OpCode.BranchTrue_s:
                case OpCode.BranchEq_s:
                case OpCode.BranchGe_s:
                case OpCode.BranchGt_s:
                case OpCode.BranchLe_s:
                case OpCode.BranchLt_s:
                case OpCode.BranchUNe_s:
                case OpCode.BranchUGe_s:
                case OpCode.BranchUGt_s:
                case OpCode.BranchULe_s:
                case OpCode.BranchULt_s:
                case OpCode.Branch:
                case OpCode.BranchFalse:
                case OpCode.BranchTrue:
                case OpCode.BranchEq:
                case OpCode.BranchGe:
                case OpCode.BranchGt:
                case OpCode.BranchLe:
                case OpCode.BranchLt:
                case OpCode.BranchUNe:
                case OpCode.BranchUGe:
                case OpCode.BranchUGt:
                case OpCode.BranchULe:
                case OpCode.BranchULt:
                case OpCode.Switch:
                    return StackPushCode.Push0;
                case OpCode.LoadIndirectInt8:
                case OpCode.LoadIndirectUInt8:
                case OpCode.LoadIndirectInt16:
                case OpCode.LoadIndirectUInt16:
                case OpCode.LoadIndirectInt32:
                case OpCode.LoadIndirectUInt32:
                case OpCode.LoadIndirectInt64:
                case OpCode.LoadIndirectIntPtr:
                case OpCode.LoadIndirectSingle:
                case OpCode.LoadIndirectDouble:
                case OpCode.LoadIndirect_ref:
                    return StackPushCode.Push1;
                case OpCode.StoreIndirect_ref:
                case OpCode.StoreIndirectInt8:
                case OpCode.StoreIndirectInt16:
                case OpCode.StoreIndirectInt32:
                case OpCode.StoreIndirectInt64:
                case OpCode.StoreIndirectSingle:
                case OpCode.StoreIndirectDouble:
                    return StackPushCode.Push0;
                case OpCode.Add:
                case OpCode.Sub:
                case OpCode.Mul:
                case OpCode.Div:
                case OpCode.Div_un:
                case OpCode.Rem:
                case OpCode.Rem_un:
                case OpCode.And:
                case OpCode.Or:
                case OpCode.Xor:
                case OpCode.Shl:
                case OpCode.Shr:
                case OpCode.Shr_un:
                case OpCode.Neg:
                case OpCode.Not:
                case OpCode.ConvertToInt8:
                case OpCode.ConvertToInt16:
                case OpCode.ConvertToInt32:
                case OpCode.ConvertToInt64:
                case OpCode.ConvertToSingle:
                case OpCode.ConvertToDouble:
                case OpCode.ConvertToUInt32:
                case OpCode.ConvertToUInt64:
                    return StackPushCode.Push1;
                case OpCode.CallVirtual:
                    return StackPushCode.PushVar;
                case OpCode.CopyObject:
                    return StackPushCode.Push0;
                case OpCode.LoadObject:
                case OpCode.LoadString:
                case OpCode.Newobj:
                case OpCode.Castclass:
                case OpCode.Isinst:
                case OpCode.Conv_r_un:
                case OpCode.Unbox:
                    return StackPushCode.Push1;
                case OpCode.Throw:
                    return StackPushCode.Push0;
                case OpCode.LoadField:
                case OpCode.LoadFieldAddress:
                    return StackPushCode.Push1;
                case OpCode.StoreField:
                    return StackPushCode.Push0;
                case OpCode.LoadStaticField:
                case OpCode.LoadStaticFieldAddress:
                    return StackPushCode.Push1;
                case OpCode.StoreStaticField:
                case OpCode.StoreObject:
                    return StackPushCode.Push0;
                case OpCode.ConvertUnsignedOverflowToInt8:
                case OpCode.ConvertUnsignedOverflowToInt16:
                case OpCode.ConvertUnsignedOverflowToInt32:
                case OpCode.ConvertUnsignedOverflowToInt64:
                case OpCode.ConvertUnsignedOverflowToUInt8:
                case OpCode.ConvertUnsignedOverflowToUInt16:
                case OpCode.ConvertUnsignedOverflowToUInt32:
                case OpCode.ConvertUnsignedOverflowToUInt64:
                case OpCode.ConvertUnsignedOverflowToIntPtr:
                case OpCode.ConvertUnsignedOverflowToUIntPtr:
                case OpCode.Box:
                case OpCode.Newarr:
                case OpCode.LoadLength:
                case OpCode.LoadElementAddress:
                case OpCode.LoadElementInt8:
                case OpCode.LoadElementUInt8:
                case OpCode.LoadElementInt16:
                case OpCode.LoadElementUInt16:
                case OpCode.LoadElementInt32:
                case OpCode.LoadElementUInt32:
                case OpCode.LoadElementInt64:
                case OpCode.LoadElementIntPtr:
                case OpCode.LoadElementSingle:
                case OpCode.LoadElementDouble:
                case OpCode.LoadElement_ref:
                    return StackPushCode.Push1;
                case OpCode.StoreElementIntPtr:
                case OpCode.StoreElementInt8:
                case OpCode.StoreElementInt16:
                case OpCode.StoreElementInt32:
                case OpCode.StoreElementInt64:
                case OpCode.StoreElementSingle:
                case OpCode.StoreElementDouble:
                case OpCode.StoreElement_ref:
                    return StackPushCode.Push0;
                case OpCode.LoadElement:
                    return StackPushCode.Push1;
                case OpCode.StoreElement:
                    return StackPushCode.Push0;
                case OpCode.Unbox_any:
                case OpCode.ConvertOverflowToInt8:
                case OpCode.ConvertOverflowToUInt8:
                case OpCode.ConvertOverflowToInt16:
                case OpCode.ConvertOverflowToUInt16:
                case OpCode.ConvertOverflowToInt32:
                case OpCode.ConvertOverflowToUInt32:
                case OpCode.ConvertOverflowToInt64:
                case OpCode.ConvertOverflowToUInt64:
                case OpCode.Refanyval:
                case OpCode.Ckfinite:
                case OpCode.Mkrefany:
                case OpCode.Ldtoken:
                case OpCode.ConvertToUInt16:
                case OpCode.ConvertToUInt8:
                case OpCode.ConvertToIntPtr:
                case OpCode.ConvertOverflowToIntPtr:
                case OpCode.ConvertOverflowToUIntPtr:
                case OpCode.Add_ovf:
                case OpCode.Add_ovf_un:
                case OpCode.Mul_ovf:
                case OpCode.Mul_ovf_un:
                case OpCode.Sub_ovf:
                case OpCode.Sub_ovf_un:
                    return StackPushCode.Push1;
                case OpCode.Endfinally:
                case OpCode.Leave:
                case OpCode.Leave_s:
                case OpCode.StoreIndirectIntPtr:
                    return StackPushCode.Push0;
                case OpCode.Conv_u:
                    return StackPushCode.Push1;
                case OpCode.Prefix7:
                case OpCode.Prefix6:
                case OpCode.Prefix5:
                case OpCode.Prefix4:
                case OpCode.Prefix3:
                case OpCode.Prefix2:
                case OpCode.Prefix1:
                case OpCode.Prefixref:
                    break;
                case OpCode.Arglist:
                case OpCode.CompareEq:
                case OpCode.CompareGt:
                case OpCode.CompareUGt:
                case OpCode.CompareLt:
                case OpCode.CompareULt:
                case OpCode.LoadFunction:
                case OpCode.LoadVirtualFunction:
                case OpCode.LoadArgument:
                case OpCode.LoadArgumentAddress:
                    return StackPushCode.Push1;
                case OpCode.StoreArgument:
                    return StackPushCode.Push0;
                case OpCode.LoadLocal:
                case OpCode.LoadLocalAddress:
                    return StackPushCode.Push1;
                case OpCode.StoreLocal:
                case OpCode.Localloc:
                case OpCode.Endfilter:
                    return StackPushCode.Push0;
                case OpCode.Unaligned:
                case OpCode.Volatile:
                    break;
                case OpCode.Tailcall:
                    return StackPushCode.PushVar;
                case OpCode.Initobj:
                    return StackPushCode.Push0;
                case OpCode.Constrained:
                    break;
                case OpCode.Cpblk:
                case OpCode.Initblk:
                case OpCode.Rethrow:
                    return StackPushCode.Push0;
                case OpCode.Sizeof:
                    return StackPushCode.Push1;
                case OpCode.Refanytype:
                    return StackPushCode.Push1;
                case OpCode.Readonly:
                    break;
            }

            throw new NotSupportedException();
        }

        public static FlowType GetFlowType(OpCode opCode)
        {
            switch (opCode)
            {
                case OpCode.Nop:
                case OpCode.Break:
                case OpCode.LoadArgument_0:
                case OpCode.LoadArgument_1:
                case OpCode.LoadArgument_2:
                case OpCode.LoadArgument_3:
                case OpCode.LoadLocal_0:
                case OpCode.LoadLocal_1:
                case OpCode.LoadLocal_2:
                case OpCode.LoadLocal_3:
                case OpCode.StoreLocal_0:
                case OpCode.StoreLocal_1:
                case OpCode.StoreLocal_2:
                case OpCode.StoreLocal_3:
                case OpCode.LoadArgument_s:
                case OpCode.LoadArgumentAddress_s:
                case OpCode.StoreArgument_s:
                case OpCode.LoadLocal_s:
                case OpCode.LoadLocalAddress_s:
                case OpCode.StoreLocal_s:
                case OpCode.LoadNull:
                case OpCode.LoadConstantInt32_m1:
                case OpCode.LoadConstantInt32_0:
                case OpCode.LoadConstantInt32_1:
                case OpCode.LoadConstantInt32_2:
                case OpCode.LoadConstantInt32_3:
                case OpCode.LoadConstantInt32_4:
                case OpCode.LoadConstantInt32_5:
                case OpCode.LoadConstantInt32_6:
                case OpCode.LoadConstantInt32_7:
                case OpCode.LoadConstantInt32_8:
                case OpCode.LoadConstantInt32_s:
                case OpCode.LoadConstantInt32:
                case OpCode.LoadConstantInt64:
                case OpCode.LoadConstantSingle:
                case OpCode.LoadConstantDouble:
                case OpCode.Dup:
                case OpCode.Pop:
                    return FlowType.Next;
                case OpCode.Jmp:
                case OpCode.Call:
                case OpCode.CallIndirect:
                    return FlowType.MethodCall;
                case OpCode.Return:
                    return FlowType.Return;
                case OpCode.Branch_s:
                    return FlowType.Branch;
                case OpCode.BranchFalse_s:
                case OpCode.BranchTrue_s:
                case OpCode.BranchEq_s:
                case OpCode.BranchGe_s:
                case OpCode.BranchGt_s:
                case OpCode.BranchLe_s:
                case OpCode.BranchLt_s:
                case OpCode.BranchUNe_s:
                case OpCode.BranchUGe_s:
                case OpCode.BranchUGt_s:
                case OpCode.BranchULe_s:
                case OpCode.BranchULt_s:
                    return FlowType.ConditionalBranch;
                case OpCode.Branch:
                    return FlowType.Branch;
                case OpCode.BranchFalse:
                case OpCode.BranchTrue:
                case OpCode.BranchEq:
                case OpCode.BranchGe:
                case OpCode.BranchGt:
                case OpCode.BranchLe:
                case OpCode.BranchLt:
                case OpCode.BranchUNe:
                case OpCode.BranchUGe:
                case OpCode.BranchUGt:
                case OpCode.BranchULe:
                case OpCode.BranchULt:
                    return FlowType.ConditionalBranch;
                case OpCode.Switch:
                    return FlowType.Switch;
                case OpCode.LoadIndirectInt8:
                case OpCode.LoadIndirectUInt8:
                case OpCode.LoadIndirectInt16:
                case OpCode.LoadIndirectUInt16:
                case OpCode.LoadIndirectInt32:
                case OpCode.LoadIndirectUInt32:
                case OpCode.LoadIndirectInt64:
                case OpCode.LoadIndirectIntPtr:
                case OpCode.LoadIndirectSingle:
                case OpCode.LoadIndirectDouble:
                case OpCode.LoadIndirect_ref:
                case OpCode.StoreIndirect_ref:
                case OpCode.StoreIndirectInt8:
                case OpCode.StoreIndirectInt16:
                case OpCode.StoreIndirectInt32:
                case OpCode.StoreIndirectInt64:
                case OpCode.StoreIndirectSingle:
                case OpCode.StoreIndirectDouble:
                case OpCode.Add:
                case OpCode.Sub:
                case OpCode.Mul:
                case OpCode.Div:
                case OpCode.Div_un:
                case OpCode.Rem:
                case OpCode.Rem_un:
                case OpCode.And:
                case OpCode.Or:
                case OpCode.Xor:
                case OpCode.Shl:
                case OpCode.Shr:
                case OpCode.Shr_un:
                case OpCode.Neg:
                case OpCode.Not:
                case OpCode.ConvertToInt8:
                case OpCode.ConvertToInt16:
                case OpCode.ConvertToInt32:
                case OpCode.ConvertToInt64:
                case OpCode.ConvertToSingle:
                case OpCode.ConvertToDouble:
                case OpCode.ConvertToUInt32:
                case OpCode.ConvertToUInt64:
                    return FlowType.Next;
                case OpCode.CallVirtual:
                    return FlowType.MethodCall;
                case OpCode.CopyObject:
                case OpCode.LoadObject:
                case OpCode.LoadString:
                    return FlowType.Next;
                case OpCode.Newobj:
                    return FlowType.MethodCall;
                case OpCode.Castclass:
                case OpCode.Isinst:
                case OpCode.Conv_r_un:
                case OpCode.Unbox:
                    return FlowType.Next;
                case OpCode.Throw:
                    return FlowType.Throw;
                case OpCode.LoadField:
                case OpCode.LoadFieldAddress:
                case OpCode.StoreField:
                case OpCode.LoadStaticField:
                case OpCode.LoadStaticFieldAddress:
                case OpCode.StoreStaticField:
                case OpCode.StoreObject:
                case OpCode.ConvertUnsignedOverflowToInt8:
                case OpCode.ConvertUnsignedOverflowToInt16:
                case OpCode.ConvertUnsignedOverflowToInt32:
                case OpCode.ConvertUnsignedOverflowToInt64:
                case OpCode.ConvertUnsignedOverflowToUInt8:
                case OpCode.ConvertUnsignedOverflowToUInt16:
                case OpCode.ConvertUnsignedOverflowToUInt32:
                case OpCode.ConvertUnsignedOverflowToUInt64:
                case OpCode.ConvertUnsignedOverflowToIntPtr:
                case OpCode.ConvertUnsignedOverflowToUIntPtr:
                case OpCode.Box:
                case OpCode.Newarr:
                case OpCode.LoadLength:
                case OpCode.LoadElementAddress:
                case OpCode.LoadElementInt8:
                case OpCode.LoadElementUInt8:
                case OpCode.LoadElementInt16:
                case OpCode.LoadElementUInt16:
                case OpCode.LoadElementInt32:
                case OpCode.LoadElementUInt32:
                case OpCode.LoadElementInt64:
                case OpCode.LoadElementIntPtr:
                case OpCode.LoadElementSingle:
                case OpCode.LoadElementDouble:
                case OpCode.LoadElement_ref:
                case OpCode.StoreElementIntPtr:
                case OpCode.StoreElementInt8:
                case OpCode.StoreElementInt16:
                case OpCode.StoreElementInt32:
                case OpCode.StoreElementInt64:
                case OpCode.StoreElementSingle:
                case OpCode.StoreElementDouble:
                case OpCode.StoreElement_ref:
                case OpCode.LoadElement:
                case OpCode.StoreElement:
                case OpCode.Unbox_any:
                case OpCode.ConvertOverflowToInt8:
                case OpCode.ConvertOverflowToUInt8:
                case OpCode.ConvertOverflowToInt16:
                case OpCode.ConvertOverflowToUInt16:
                case OpCode.ConvertOverflowToInt32:
                case OpCode.ConvertOverflowToUInt32:
                case OpCode.ConvertOverflowToInt64:
                case OpCode.ConvertOverflowToUInt64:
                case OpCode.Refanyval:
                case OpCode.Ckfinite:
                case OpCode.Mkrefany:
                case OpCode.Ldtoken:
                case OpCode.ConvertToUInt16:
                case OpCode.ConvertToUInt8:
                case OpCode.ConvertToIntPtr:
                case OpCode.ConvertOverflowToIntPtr:
                case OpCode.ConvertOverflowToUIntPtr:
                case OpCode.Add_ovf:
                case OpCode.Add_ovf_un:
                case OpCode.Mul_ovf:
                case OpCode.Mul_ovf_un:
                case OpCode.Sub_ovf:
                case OpCode.Sub_ovf_un:
                    return FlowType.Next;
                case OpCode.Endfinally:
                    return FlowType.Unsuported;
                case OpCode.Leave:
                case OpCode.Leave_s:
                    return FlowType.Branch;
                case OpCode.StoreIndirectIntPtr:
                case OpCode.Conv_u:
                case OpCode.Prefix7:
                case OpCode.Prefix6:
                case OpCode.Prefix5:
                case OpCode.Prefix4:
                case OpCode.Prefix3:
                case OpCode.Prefix2:
                case OpCode.Prefix1:
                case OpCode.Prefixref:
                case OpCode.Arglist:
                case OpCode.CompareEq:
                case OpCode.CompareGt:
                case OpCode.CompareUGt:
                case OpCode.CompareLt:
                case OpCode.CompareULt:
                case OpCode.LoadFunction:
                case OpCode.LoadVirtualFunction:
                case OpCode.LoadArgument:
                case OpCode.LoadArgumentAddress:
                case OpCode.StoreArgument:
                case OpCode.LoadLocal:
                case OpCode.LoadLocalAddress:
                case OpCode.StoreLocal:
                case OpCode.Localloc:
                    return FlowType.Next;
                case OpCode.Endfilter:
                    return FlowType.Unsuported;
                case OpCode.Unaligned:
                case OpCode.Volatile:
                    return FlowType.Next;
                case OpCode.Tailcall:
                    return FlowType.Unsuported;;
                case OpCode.Initobj:
                case OpCode.Constrained:
                case OpCode.Cpblk:
                case OpCode.Initblk:
                    return FlowType.Next;
                case OpCode.Rethrow:
                    return FlowType.Throw;
                case OpCode.Sizeof:
                case OpCode.Refanytype:
                case OpCode.Readonly:
                    return FlowType.Next;
            }

            throw new NotSupportedException();
        }

        public static OpArgumentType GetArgumentType(OpCode opCode)
        {
            switch (opCode)
            {
                case OpCode.Nop:
                    return OpArgumentType.None;
                case OpCode.Break:
                    return OpArgumentType.BranchTarget;
                case OpCode.LoadArgument_0:
                case OpCode.LoadArgument_1:
                case OpCode.LoadArgument_2:
                case OpCode.LoadArgument_3:
                case OpCode.LoadLocal_0:
                case OpCode.LoadLocal_1:
                case OpCode.LoadLocal_2:
                case OpCode.LoadLocal_3:
                case OpCode.StoreLocal_0:
                case OpCode.StoreLocal_1:
                case OpCode.StoreLocal_2:
                case OpCode.StoreLocal_3:
                    return OpArgumentType.None;
                case OpCode.LoadArgument_s:
                case OpCode.LoadArgumentAddress_s:
                case OpCode.StoreArgument_s:
                case OpCode.LoadLocal_s:
                case OpCode.LoadLocalAddress_s:
                case OpCode.StoreLocal_s:
                    return OpArgumentType.Constant;
                case OpCode.LoadNull:
                case OpCode.LoadConstantInt32_m1:
                case OpCode.LoadConstantInt32_0:
                case OpCode.LoadConstantInt32_1:
                case OpCode.LoadConstantInt32_2:
                case OpCode.LoadConstantInt32_3:
                case OpCode.LoadConstantInt32_4:
                case OpCode.LoadConstantInt32_5:
                case OpCode.LoadConstantInt32_6:
                case OpCode.LoadConstantInt32_7:
                case OpCode.LoadConstantInt32_8:
                    return OpArgumentType.None;
                case OpCode.LoadConstantInt32_s:
                case OpCode.LoadConstantInt32:
                case OpCode.LoadConstantInt64:
                    return OpArgumentType.Constant;
                case OpCode.LoadConstantSingle:
                case OpCode.LoadConstantDouble:
                    return OpArgumentType.ConstantDouble;
                case OpCode.Dup:
                case OpCode.Pop:
                    return OpArgumentType.None;
                case OpCode.Jmp:
                case OpCode.Call:
                case OpCode.CallIndirect:
                    return OpArgumentType.Method;
                case OpCode.Return:
                    return OpArgumentType.None;
                case OpCode.Branch_s:
                case OpCode.BranchFalse_s:
                case OpCode.BranchTrue_s:
                case OpCode.BranchEq_s:
                case OpCode.BranchGe_s:
                case OpCode.BranchGt_s:
                case OpCode.BranchLe_s:
                case OpCode.BranchLt_s:
                case OpCode.BranchUNe_s:
                case OpCode.BranchUGe_s:
                case OpCode.BranchUGt_s:
                case OpCode.BranchULe_s:
                case OpCode.BranchULt_s:
                case OpCode.Branch:
                case OpCode.BranchFalse:
                case OpCode.BranchTrue:
                case OpCode.BranchEq:
                case OpCode.BranchGe:
                case OpCode.BranchGt:
                case OpCode.BranchLe:
                case OpCode.BranchLt:
                case OpCode.BranchUNe:
                case OpCode.BranchUGe:
                case OpCode.BranchUGt:
                case OpCode.BranchULe:
                case OpCode.BranchULt:
                    return OpArgumentType.BranchTarget;
                case OpCode.Switch:
                    return OpArgumentType.SwitchTargets;
                case OpCode.LoadIndirectInt8:
                case OpCode.LoadIndirectUInt8:
                case OpCode.LoadIndirectInt16:
                case OpCode.LoadIndirectUInt16:
                case OpCode.LoadIndirectInt32:
                case OpCode.LoadIndirectUInt32:
                case OpCode.LoadIndirectInt64:
                case OpCode.LoadIndirectIntPtr:
                case OpCode.LoadIndirectSingle:
                case OpCode.LoadIndirectDouble:
                case OpCode.LoadIndirect_ref:
                case OpCode.StoreIndirect_ref:
                case OpCode.StoreIndirectInt8:
                case OpCode.StoreIndirectInt16:
                case OpCode.StoreIndirectInt32:
                case OpCode.StoreIndirectInt64:
                case OpCode.StoreIndirectSingle:
                case OpCode.StoreIndirectDouble:
                case OpCode.Add:
                case OpCode.Sub:
                case OpCode.Mul:
                case OpCode.Div:
                case OpCode.Div_un:
                case OpCode.Rem:
                case OpCode.Rem_un:
                case OpCode.And:
                case OpCode.Or:
                case OpCode.Xor:
                case OpCode.Shl:
                case OpCode.Shr:
                case OpCode.Shr_un:
                case OpCode.Neg:
                case OpCode.Not:
                case OpCode.ConvertToInt8:
                case OpCode.ConvertToInt16:
                case OpCode.ConvertToInt32:
                case OpCode.ConvertToInt64:
                case OpCode.ConvertToSingle:
                case OpCode.ConvertToDouble:
                case OpCode.ConvertToUInt32:
                case OpCode.ConvertToUInt64:
                    return OpArgumentType.None;
                case OpCode.CallVirtual:
                    return OpArgumentType.Method;
                case OpCode.CopyObject:
                case OpCode.LoadObject:
                    return OpArgumentType.ObjectType;
                case OpCode.LoadString:
                    return OpArgumentType.ConstantString;
                case OpCode.Newobj:
                    return OpArgumentType.Method;
                case OpCode.Castclass:
                case OpCode.Isinst:
                    return OpArgumentType.ObjectType;
                case OpCode.Conv_r_un:
                    return OpArgumentType.None;
                case OpCode.Unbox:
                    return OpArgumentType.ObjectType;
                case OpCode.Throw:
                    return OpArgumentType.None;
                case OpCode.LoadField:
                case OpCode.LoadFieldAddress:
                case OpCode.StoreField:
                case OpCode.LoadStaticField:
                case OpCode.LoadStaticFieldAddress:
                case OpCode.StoreStaticField:
                    return OpArgumentType.Field;
                case OpCode.StoreObject:
                    return OpArgumentType.ObjectType;
                case OpCode.ConvertUnsignedOverflowToInt8:
                case OpCode.ConvertUnsignedOverflowToInt16:
                case OpCode.ConvertUnsignedOverflowToInt32:
                case OpCode.ConvertUnsignedOverflowToInt64:
                case OpCode.ConvertUnsignedOverflowToUInt8:
                case OpCode.ConvertUnsignedOverflowToUInt16:
                case OpCode.ConvertUnsignedOverflowToUInt32:
                case OpCode.ConvertUnsignedOverflowToUInt64:
                case OpCode.ConvertUnsignedOverflowToIntPtr:
                case OpCode.ConvertUnsignedOverflowToUIntPtr:
                    return OpArgumentType.None;
                case OpCode.Box:
                case OpCode.Newarr:
                    return OpArgumentType.ObjectType;
                case OpCode.LoadLength:
                case OpCode.LoadElementAddress:
                case OpCode.LoadElementInt8:
                case OpCode.LoadElementUInt8:
                case OpCode.LoadElementInt16:
                case OpCode.LoadElementUInt16:
                case OpCode.LoadElementInt32:
                case OpCode.LoadElementUInt32:
                case OpCode.LoadElementInt64:
                case OpCode.LoadElementIntPtr:
                case OpCode.LoadElementSingle:
                case OpCode.LoadElementDouble:
                case OpCode.LoadElement_ref:
                case OpCode.StoreElementIntPtr:
                case OpCode.StoreElementInt8:
                case OpCode.StoreElementInt16:
                case OpCode.StoreElementInt32:
                case OpCode.StoreElementInt64:
                case OpCode.StoreElementSingle:
                case OpCode.StoreElementDouble:
                case OpCode.StoreElement_ref:
                case OpCode.LoadElement:
                case OpCode.StoreElement:
                    return OpArgumentType.None;
                case OpCode.Unbox_any:
                    return OpArgumentType.ObjectType;
                case OpCode.ConvertOverflowToInt8:
                case OpCode.ConvertOverflowToUInt8:
                case OpCode.ConvertOverflowToInt16:
                case OpCode.ConvertOverflowToUInt16:
                case OpCode.ConvertOverflowToInt32:
                case OpCode.ConvertOverflowToUInt32:
                case OpCode.ConvertOverflowToInt64:
                case OpCode.ConvertOverflowToUInt64:
                    return OpArgumentType.None;
                case OpCode.Refanyval:
                    return OpArgumentType.ObjectType;
                case OpCode.Ckfinite:
                    return OpArgumentType.None;
                case OpCode.Mkrefany:
                    return OpArgumentType.ObjectType;
                case OpCode.Ldtoken:
                case OpCode.ConvertToUInt16:
                case OpCode.ConvertToUInt8:
                case OpCode.ConvertToIntPtr:
                case OpCode.ConvertOverflowToIntPtr:
                case OpCode.ConvertOverflowToUIntPtr:
                case OpCode.Add_ovf:
                case OpCode.Add_ovf_un:
                case OpCode.Mul_ovf:
                case OpCode.Mul_ovf_un:
                case OpCode.Sub_ovf:
                case OpCode.Sub_ovf_un:
                case OpCode.Endfinally:
                    return OpArgumentType.None;
                case OpCode.Leave:
                case OpCode.Leave_s:
                    return OpArgumentType.BranchTarget;
                case OpCode.StoreIndirectIntPtr:
                case OpCode.Conv_u:
                case OpCode.Prefix7:
                case OpCode.Prefix6:
                case OpCode.Prefix5:
                case OpCode.Prefix4:
                case OpCode.Prefix3:
                case OpCode.Prefix2:
                case OpCode.Prefix1:
                case OpCode.Prefixref:
                case OpCode.Arglist:
                case OpCode.CompareEq:
                case OpCode.CompareGt:
                case OpCode.CompareUGt:
                case OpCode.CompareLt:
                case OpCode.CompareULt:
                case OpCode.LoadFunction:
                    return OpArgumentType.None;
                case OpCode.LoadVirtualFunction:
                    return OpArgumentType.Method;
                case OpCode.LoadArgument:
                case OpCode.LoadArgumentAddress:
                case OpCode.StoreArgument:
                case OpCode.LoadLocal:
                case OpCode.LoadLocalAddress:
                case OpCode.StoreLocal:
                case OpCode.Localloc:
                case OpCode.Endfilter:
                case OpCode.Unaligned:
                case OpCode.Volatile:
                    return OpArgumentType.None;
                case OpCode.Tailcall:
                    return OpArgumentType.Method;
                case OpCode.Initobj:
                    return OpArgumentType.ObjectType;
                case OpCode.Constrained:
                    break;
                case OpCode.Cpblk:
                case OpCode.Initblk:
                case OpCode.Rethrow:
                    return OpArgumentType.None;
                case OpCode.Sizeof:
                    return OpArgumentType.ObjectType;
                case OpCode.Refanytype:
                case OpCode.Readonly:
                    return OpArgumentType.None;
            }

            throw new NotSupportedException();
        }
    }
}
