namespace Cs2JsC.CLR.Decompiler
{
    using System;
    using Mono.Cecil;
    using Mono.Cecil.Cil;

    internal static class OpCodeHelper
    {
        /// <summary>
        /// Gets the pops.
        /// </summary>
        /// <param name="opCode">The op code.</param>
        /// <returns>Pop code for number of stack pops.</returns>
        public static StackPopCode GetPops(OpCode opCode)
        {
            switch (opCode)
            {
                case OpCode.Nop:
                case OpCode.Break:
                case OpCode.LoadArgument_0:
                case OpCode.LoadArgument_1:
                case OpCode.LoadArgument_2:
                case OpCode.LoadArgument_3:
                case OpCode.LoadLocal_0:
                case OpCode.LoadLocal_1:
                case OpCode.LoadLocal_2:
                case OpCode.LoadLocal_3:
                case OpCode.LoadArgument_s:
                case OpCode.LoadArgumentAddress_s:
                case OpCode.LoadLocal_s:
                case OpCode.LoadLocalAddress_s:
                case OpCode.LoadNull:
                case OpCode.LoadConstantInt32_m1:
                case OpCode.LoadConstantInt32_0:
                case OpCode.LoadConstantInt32_1:
                case OpCode.LoadConstantInt32_2:
                case OpCode.LoadConstantInt32_3:
                case OpCode.LoadConstantInt32_4:
                case OpCode.LoadConstantInt32_5:
                case OpCode.LoadConstantInt32_6:
                case OpCode.LoadConstantInt32_7:
                case OpCode.LoadConstantInt32_8:
                case OpCode.LoadConstantInt32_s:
                case OpCode.LoadConstantInt32:
                case OpCode.LoadConstantInt64:
                case OpCode.LoadConstantSingle:
                case OpCode.LoadConstantDouble:
                case OpCode.Jmp:
                case OpCode.Branch_s:
                case OpCode.Branch:
                case OpCode.LoadString:
                case OpCode.Arglist:
                case OpCode.LoadArgument:
                case OpCode.LoadArgumentAddress:
                case OpCode.LoadStaticField:
                case OpCode.LoadStaticFieldAddress:
                case OpCode.LoadLocal:
                case OpCode.LoadLocalAddress:
                case OpCode.Endfinally:
                case OpCode.Rethrow:
                case OpCode.Ldtoken:
                case OpCode.LoadFunction:
                case OpCode.DupCopy:
                case OpCode.CatchEntry:
                case OpCode.LoadDefaultValue:
                    return StackPopCode.Pop0;
                case OpCode.StoreLocal_0:
                case OpCode.StoreLocal_1:
                case OpCode.StoreLocal_2:
                case OpCode.StoreLocal_3:
                case OpCode.StoreArgument_s:
                case OpCode.StoreLocal_s:
                case OpCode.Dup:
                case OpCode.Pop:
                case OpCode.LoadIndirectInt8:
                case OpCode.LoadIndirectUInt8:
                case OpCode.LoadIndirectInt16:
                case OpCode.LoadIndirectUInt16:
                case OpCode.LoadIndirectInt32:
                case OpCode.LoadIndirectUInt32:
                case OpCode.LoadIndirectInt64:
                case OpCode.LoadIndirectIntPtr:
                case OpCode.LoadIndirectSingle:
                case OpCode.LoadIndirectDouble:
                case OpCode.LoadIndirect_ref:
                case OpCode.Neg:
                case OpCode.Not:
                case OpCode.ConvertToInt8:
                case OpCode.ConvertToInt16:
                case OpCode.ConvertToInt32:
                case OpCode.ConvertToInt64:
                case OpCode.ConvertToSingle:
                case OpCode.ConvertToDouble:
                case OpCode.ConvertToUInt32:
                case OpCode.ConvertToUInt64:
                case OpCode.LoadObject:
                case OpCode.Castclass:
                case OpCode.Isinst:
                case OpCode.Box:
                case OpCode.Unbox:
                case OpCode.Throw:
                case OpCode.LoadField:
                case OpCode.LoadFieldAddress:
                case OpCode.ConvertUnsignedOverflowToInt8:
                case OpCode.ConvertUnsignedOverflowToInt16:
                case OpCode.ConvertUnsignedOverflowToInt32:
                case OpCode.ConvertUnsignedOverflowToInt64:
                case OpCode.ConvertUnsignedOverflowToUInt8:
                case OpCode.ConvertUnsignedOverflowToUInt16:
                case OpCode.ConvertUnsignedOverflowToUInt32:
                case OpCode.ConvertUnsignedOverflowToUInt64:
                case OpCode.ConvertUnsignedOverflowToIntPtr:
                case OpCode.ConvertUnsignedOverflowToUIntPtr:
                case OpCode.Newarr:
                case OpCode.LoadLength:
                case OpCode.Unbox_any:
                case OpCode.Refanyval:
                case OpCode.Ckfinite:
                case OpCode.Mkrefany:
                case OpCode.ConvertToUInt16:
                case OpCode.ConvertToUInt8:
                case OpCode.ConvertToIntPtr:
                case OpCode.ConvertOverflowToIntPtr:
                case OpCode.ConvertOverflowToUIntPtr:
                case OpCode.Conv_u:
                case OpCode.LoadVirtualFunction:
                case OpCode.StoreArgument:
                case OpCode.StoreLocal:
                case OpCode.StoreStaticField:
                case OpCode.Endfilter:
                case OpCode.Localloc:
                case OpCode.Sizeof:
                case OpCode.Refanytype:
                case OpCode.BranchFalse_s:
                case OpCode.BranchTrue_s:
                case OpCode.BranchFalse:
                case OpCode.BranchTrue:
                case OpCode.Switch:
                case OpCode.Initobj:
                    return StackPopCode.Pop1;
                case OpCode.StoreIndirect_ref:
                case OpCode.StoreIndirectInt8:
                case OpCode.StoreIndirectInt16:
                case OpCode.StoreIndirectInt32:
                case OpCode.StoreIndirectInt64:
                case OpCode.StoreIndirectSingle:
                case OpCode.StoreIndirectDouble:
                case OpCode.Add:
                case OpCode.Sub:
                case OpCode.Mul:
                case OpCode.Div:
                case OpCode.Div_un:
                case OpCode.Rem:
                case OpCode.Rem_un:
                case OpCode.And:
                case OpCode.Or:
                case OpCode.Xor:
                case OpCode.Shl:
                case OpCode.Shr:
                case OpCode.Shr_un:
                case OpCode.CopyObject:
                case OpCode.StoreField:
                case OpCode.StoreObject:
                case OpCode.LoadElementAddress:
                case OpCode.LoadElementInt8:
                case OpCode.LoadElementUInt8:
                case OpCode.LoadElementInt16:
                case OpCode.LoadElementUInt16:
                case OpCode.LoadElementInt32:
                case OpCode.LoadElementUInt32:
                case OpCode.LoadElementInt64:
                case OpCode.LoadElementIntPtr:
                case OpCode.LoadElementSingle:
                case OpCode.LoadElementDouble:
                case OpCode.LoadElement_ref:
                case OpCode.LoadElement:
                case OpCode.Add_ovf:
                case OpCode.Add_ovf_un:
                case OpCode.Mul_ovf:
                case OpCode.Mul_ovf_un:
                case OpCode.Sub_ovf:
                case OpCode.Sub_ovf_un:
                case OpCode.StoreIndirectIntPtr:
                case OpCode.CompareEq:
                case OpCode.CompareGt:
                case OpCode.CompareUGt:
                case OpCode.CompareLt:
                case OpCode.CompareULt:
                case OpCode.BranchEq_s:
                case OpCode.BranchGe_s:
                case OpCode.BranchGt_s:
                case OpCode.BranchLe_s:
                case OpCode.BranchLt_s:
                case OpCode.BranchUNe_s:
                case OpCode.BranchUGe_s:
                case OpCode.BranchUGt_s:
                case OpCode.BranchULe_s:
                case OpCode.BranchULt_s:
                case OpCode.BranchEq:
                case OpCode.BranchGe:
                case OpCode.BranchGt:
                case OpCode.BranchLe:
                case OpCode.BranchLt:
                case OpCode.BranchUNe:
                case OpCode.BranchUGe:
                case OpCode.BranchUGt:
                case OpCode.BranchULe:
                case OpCode.BranchULt:
                    return StackPopCode.Pop2;
                case OpCode.StoreElementIntPtr:
                case OpCode.StoreElementInt8:
                case OpCode.StoreElementInt16:
                case OpCode.StoreElementInt32:
                case OpCode.StoreElementInt64:
                case OpCode.StoreElementSingle:
                case OpCode.StoreElementDouble:
                case OpCode.StoreElement_ref:
                case OpCode.StoreElement:
                case OpCode.Cpblk:
                case OpCode.Initblk:
                    return StackPopCode.Pop3;
                case OpCode.Call:
                case OpCode.CallIndirect:
                case OpCode.CallVirtual:
                case OpCode.Newobj:
                case OpCode.Tailcall:
                    return StackPopCode.PopVar;
                case OpCode.Return:
                    return StackPopCode.PopAll;
                case OpCode.Leave:
                case OpCode.Leave_s:
                    return StackPopCode.Pop0;
                case OpCode.Constrained:
                    return StackPopCode.Pop1;
                case OpCode.Conv_r_un:
                case OpCode.Prefix7:
                case OpCode.Prefix6:
                case OpCode.Prefix5:
                case OpCode.Prefix4:
                case OpCode.Prefix3:
                case OpCode.Prefix2:
                case OpCode.Prefix1:
                case OpCode.Prefixref:
                case OpCode.Unaligned:
                case OpCode.Volatile:
                case OpCode.Readonly:
                default:
                    throw new NotSupportedException();
            }
        }

        /// <summary>
        /// Gets the pushes.
        /// </summary>
        /// <param name="opCode">The op code.</param>
        /// <returns>Push code for number of stack pushes.</returns>
        public static StackPushCode GetPushes(OpCode opCode)
        {
            switch (opCode)
            {
                case OpCode.Nop:
                case OpCode.Break:
                    return StackPushCode.Push0;
                case OpCode.LoadArgument_0:
                case OpCode.LoadArgument_1:
                case OpCode.LoadArgument_2:
                case OpCode.LoadArgument_3:
                case OpCode.LoadLocal_0:
                case OpCode.LoadLocal_1:
                case OpCode.LoadLocal_2:
                case OpCode.LoadLocal_3:
                    return StackPushCode.Push1;
                case OpCode.StoreLocal_0:
                case OpCode.StoreLocal_1:
                case OpCode.StoreLocal_2:
                case OpCode.StoreLocal_3:
                    return StackPushCode.Push0;
                case OpCode.LoadArgument_s:
                case OpCode.LoadArgumentAddress_s:
                    return StackPushCode.Push1;
                case OpCode.StoreArgument_s:
                    return StackPushCode.Push0;
                case OpCode.LoadLocal_s:
                case OpCode.LoadLocalAddress_s:
                    return StackPushCode.Push1;
                case OpCode.StoreLocal_s:
                    return StackPushCode.Push0;
                case OpCode.LoadNull:
                case OpCode.LoadConstantInt32_m1:
                case OpCode.LoadConstantInt32_0:
                case OpCode.LoadConstantInt32_1:
                case OpCode.LoadConstantInt32_2:
                case OpCode.LoadConstantInt32_3:
                case OpCode.LoadConstantInt32_4:
                case OpCode.LoadConstantInt32_5:
                case OpCode.LoadConstantInt32_6:
                case OpCode.LoadConstantInt32_7:
                case OpCode.LoadConstantInt32_8:
                case OpCode.LoadConstantInt32_s:
                case OpCode.LoadConstantInt32:
                case OpCode.LoadConstantInt64:
                case OpCode.LoadConstantSingle:
                case OpCode.LoadConstantDouble:
                case OpCode.Dup:
                case OpCode.DupCopy:
                case OpCode.CatchEntry:
                case OpCode.LoadDefaultValue:
                    return StackPushCode.Push1;
                case OpCode.Pop:
                case OpCode.Jmp:
                    return StackPushCode.Push0;
                case OpCode.Call:
                case OpCode.CallIndirect:
                    return StackPushCode.PushVar;
                case OpCode.Return:
                    return StackPushCode.Push0;
                case OpCode.Branch_s:
                case OpCode.BranchFalse_s:
                case OpCode.BranchTrue_s:
                case OpCode.BranchEq_s:
                case OpCode.BranchGe_s:
                case OpCode.BranchGt_s:
                case OpCode.BranchLe_s:
                case OpCode.BranchLt_s:
                case OpCode.BranchUNe_s:
                case OpCode.BranchUGe_s:
                case OpCode.BranchUGt_s:
                case OpCode.BranchULe_s:
                case OpCode.BranchULt_s:
                case OpCode.Branch:
                case OpCode.BranchFalse:
                case OpCode.BranchTrue:
                case OpCode.BranchEq:
                case OpCode.BranchGe:
                case OpCode.BranchGt:
                case OpCode.BranchLe:
                case OpCode.BranchLt:
                case OpCode.BranchUNe:
                case OpCode.BranchUGe:
                case OpCode.BranchUGt:
                case OpCode.BranchULe:
                case OpCode.BranchULt:
                case OpCode.Switch:
                    return StackPushCode.Push0;
                case OpCode.LoadIndirectInt8:
                case OpCode.LoadIndirectUInt8:
                case OpCode.LoadIndirectInt16:
                case OpCode.LoadIndirectUInt16:
                case OpCode.LoadIndirectInt32:
                case OpCode.LoadIndirectUInt32:
                case OpCode.LoadIndirectInt64:
                case OpCode.LoadIndirectIntPtr:
                case OpCode.LoadIndirectSingle:
                case OpCode.LoadIndirectDouble:
                case OpCode.LoadIndirect_ref:
                    return StackPushCode.Push1;
                case OpCode.StoreIndirect_ref:
                case OpCode.StoreIndirectInt8:
                case OpCode.StoreIndirectInt16:
                case OpCode.StoreIndirectInt32:
                case OpCode.StoreIndirectInt64:
                case OpCode.StoreIndirectSingle:
                case OpCode.StoreIndirectDouble:
                    return StackPushCode.Push0;
                case OpCode.Add:
                case OpCode.Sub:
                case OpCode.Mul:
                case OpCode.Div:
                case OpCode.Div_un:
                case OpCode.Rem:
                case OpCode.Rem_un:
                case OpCode.And:
                case OpCode.Or:
                case OpCode.Xor:
                case OpCode.Shl:
                case OpCode.Shr:
                case OpCode.Shr_un:
                case OpCode.Neg:
                case OpCode.Not:
                case OpCode.ConvertToInt8:
                case OpCode.ConvertToInt16:
                case OpCode.ConvertToInt32:
                case OpCode.ConvertToInt64:
                case OpCode.ConvertToSingle:
                case OpCode.ConvertToDouble:
                case OpCode.ConvertToUInt32:
                case OpCode.ConvertToUInt64:
                    return StackPushCode.Push1;
                case OpCode.CallVirtual:
                    return StackPushCode.PushVar;
                case OpCode.CopyObject:
                    return StackPushCode.Push0;
                case OpCode.LoadObject:
                case OpCode.LoadString:
                case OpCode.Newobj:
                case OpCode.Castclass:
                case OpCode.Isinst:
                case OpCode.Conv_r_un:
                case OpCode.Unbox:
                    return StackPushCode.Push1;
                case OpCode.Throw:
                    return StackPushCode.Push0;
                case OpCode.LoadField:
                case OpCode.LoadFieldAddress:
                    return StackPushCode.Push1;
                case OpCode.StoreField:
                    return StackPushCode.Push0;
                case OpCode.LoadStaticField:
                case OpCode.LoadStaticFieldAddress:
                    return StackPushCode.Push1;
                case OpCode.StoreStaticField:
                case OpCode.StoreObject:
                    return StackPushCode.Push0;
                case OpCode.ConvertUnsignedOverflowToInt8:
                case OpCode.ConvertUnsignedOverflowToInt16:
                case OpCode.ConvertUnsignedOverflowToInt32:
                case OpCode.ConvertUnsignedOverflowToInt64:
                case OpCode.ConvertUnsignedOverflowToUInt8:
                case OpCode.ConvertUnsignedOverflowToUInt16:
                case OpCode.ConvertUnsignedOverflowToUInt32:
                case OpCode.ConvertUnsignedOverflowToUInt64:
                case OpCode.ConvertUnsignedOverflowToIntPtr:
                case OpCode.ConvertUnsignedOverflowToUIntPtr:
                case OpCode.Box:
                case OpCode.Newarr:
                case OpCode.LoadLength:
                case OpCode.LoadElementAddress:
                case OpCode.LoadElementInt8:
                case OpCode.LoadElementUInt8:
                case OpCode.LoadElementInt16:
                case OpCode.LoadElementUInt16:
                case OpCode.LoadElementInt32:
                case OpCode.LoadElementUInt32:
                case OpCode.LoadElementInt64:
                case OpCode.LoadElementIntPtr:
                case OpCode.LoadElementSingle:
                case OpCode.LoadElementDouble:
                case OpCode.LoadElement_ref:
                    return StackPushCode.Push1;
                case OpCode.StoreElementIntPtr:
                case OpCode.StoreElementInt8:
                case OpCode.StoreElementInt16:
                case OpCode.StoreElementInt32:
                case OpCode.StoreElementInt64:
                case OpCode.StoreElementSingle:
                case OpCode.StoreElementDouble:
                case OpCode.StoreElement_ref:
                    return StackPushCode.Push0;
                case OpCode.LoadElement:
                    return StackPushCode.Push1;
                case OpCode.StoreElement:
                    return StackPushCode.Push0;
                case OpCode.Unbox_any:
                case OpCode.ConvertOverflowToInt8:
                case OpCode.ConvertOverflowToUInt8:
                case OpCode.ConvertOverflowToInt16:
                case OpCode.ConvertOverflowToUInt16:
                case OpCode.ConvertOverflowToInt32:
                case OpCode.ConvertOverflowToUInt32:
                case OpCode.ConvertOverflowToInt64:
                case OpCode.ConvertOverflowToUInt64:
                case OpCode.Refanyval:
                case OpCode.Ckfinite:
                case OpCode.Mkrefany:
                case OpCode.Ldtoken:
                case OpCode.ConvertToUInt16:
                case OpCode.ConvertToUInt8:
                case OpCode.ConvertToIntPtr:
                case OpCode.ConvertOverflowToIntPtr:
                case OpCode.ConvertOverflowToUIntPtr:
                case OpCode.Add_ovf:
                case OpCode.Add_ovf_un:
                case OpCode.Mul_ovf:
                case OpCode.Mul_ovf_un:
                case OpCode.Sub_ovf:
                case OpCode.Sub_ovf_un:
                    return StackPushCode.Push1;
                case OpCode.Endfinally:
                case OpCode.Leave:
                case OpCode.Leave_s:
                case OpCode.StoreIndirectIntPtr:
                    return StackPushCode.Push0;
                case OpCode.Conv_u:
                    return StackPushCode.Push1;
                case OpCode.Prefix7:
                case OpCode.Prefix6:
                case OpCode.Prefix5:
                case OpCode.Prefix4:
                case OpCode.Prefix3:
                case OpCode.Prefix2:
                case OpCode.Prefix1:
                case OpCode.Prefixref:
                    break;
                case OpCode.Arglist:
                case OpCode.CompareEq:
                case OpCode.CompareGt:
                case OpCode.CompareUGt:
                case OpCode.CompareLt:
                case OpCode.CompareULt:
                case OpCode.LoadFunction:
                case OpCode.LoadVirtualFunction:
                case OpCode.LoadArgument:
                case OpCode.LoadArgumentAddress:
                    return StackPushCode.Push1;
                case OpCode.StoreArgument:
                    return StackPushCode.Push0;
                case OpCode.LoadLocal:
                case OpCode.LoadLocalAddress:
                    return StackPushCode.Push1;
                case OpCode.StoreLocal:
                case OpCode.Localloc:
                case OpCode.Endfilter:
                    return StackPushCode.Push0;
                case OpCode.Unaligned:
                case OpCode.Volatile:
                    break;
                case OpCode.Tailcall:
                    return StackPushCode.PushVar;
                case OpCode.Initobj:
                    return StackPushCode.Push0;
                case OpCode.Constrained:
                    return StackPushCode.Push1;
                case OpCode.Cpblk:
                case OpCode.Initblk:
                case OpCode.Rethrow:
                    return StackPushCode.Push0;
                case OpCode.Sizeof:
                    return StackPushCode.Push1;
                case OpCode.Refanytype:
                    return StackPushCode.Push1;
                case OpCode.Readonly:
                    break;
            }

            throw new NotSupportedException();
        }

        /// <summary>
        /// Gets the type of the flow.
        /// </summary>
        /// <param name="opCode">The op code.</param>
        /// <returns>Flow type for the opcode.</returns>
        public static FlowType GetFlowType(OpCode opCode)
        {
            switch (opCode)
            {
                case OpCode.Nop:
                case OpCode.Break:
                case OpCode.LoadArgument_0:
                case OpCode.LoadArgument_1:
                case OpCode.LoadArgument_2:
                case OpCode.LoadArgument_3:
                case OpCode.LoadLocal_0:
                case OpCode.LoadLocal_1:
                case OpCode.LoadLocal_2:
                case OpCode.LoadLocal_3:
                case OpCode.StoreLocal_0:
                case OpCode.StoreLocal_1:
                case OpCode.StoreLocal_2:
                case OpCode.StoreLocal_3:
                case OpCode.LoadArgument_s:
                case OpCode.LoadArgumentAddress_s:
                case OpCode.StoreArgument_s:
                case OpCode.LoadLocal_s:
                case OpCode.LoadLocalAddress_s:
                case OpCode.StoreLocal_s:
                case OpCode.LoadNull:
                case OpCode.LoadConstantInt32_m1:
                case OpCode.LoadConstantInt32_0:
                case OpCode.LoadConstantInt32_1:
                case OpCode.LoadConstantInt32_2:
                case OpCode.LoadConstantInt32_3:
                case OpCode.LoadConstantInt32_4:
                case OpCode.LoadConstantInt32_5:
                case OpCode.LoadConstantInt32_6:
                case OpCode.LoadConstantInt32_7:
                case OpCode.LoadConstantInt32_8:
                case OpCode.LoadConstantInt32_s:
                case OpCode.LoadConstantInt32:
                case OpCode.LoadConstantInt64:
                case OpCode.LoadConstantSingle:
                case OpCode.LoadConstantDouble:
                case OpCode.Dup:
                case OpCode.DupCopy:
                case OpCode.Pop:
                case OpCode.CatchEntry:
                case OpCode.LoadDefaultValue:
                    return FlowType.Next;
                case OpCode.Jmp:
                case OpCode.Call:
                case OpCode.CallIndirect:
                    return FlowType.MethodCall;
                case OpCode.Return:
                    return FlowType.Return;
                case OpCode.Branch_s:
                    return FlowType.Branch;
                case OpCode.BranchFalse_s:
                case OpCode.BranchTrue_s:
                case OpCode.BranchEq_s:
                case OpCode.BranchGe_s:
                case OpCode.BranchGt_s:
                case OpCode.BranchLe_s:
                case OpCode.BranchLt_s:
                case OpCode.BranchUNe_s:
                case OpCode.BranchUGe_s:
                case OpCode.BranchUGt_s:
                case OpCode.BranchULe_s:
                case OpCode.BranchULt_s:
                    return FlowType.ConditionalBranch;
                case OpCode.Branch:
                    return FlowType.Branch;
                case OpCode.BranchFalse:
                case OpCode.BranchTrue:
                case OpCode.BranchEq:
                case OpCode.BranchGe:
                case OpCode.BranchGt:
                case OpCode.BranchLe:
                case OpCode.BranchLt:
                case OpCode.BranchUNe:
                case OpCode.BranchUGe:
                case OpCode.BranchUGt:
                case OpCode.BranchULe:
                case OpCode.BranchULt:
                    return FlowType.ConditionalBranch;
                case OpCode.Switch:
                    return FlowType.Switch;
                case OpCode.LoadIndirectInt8:
                case OpCode.LoadIndirectUInt8:
                case OpCode.LoadIndirectInt16:
                case OpCode.LoadIndirectUInt16:
                case OpCode.LoadIndirectInt32:
                case OpCode.LoadIndirectUInt32:
                case OpCode.LoadIndirectInt64:
                case OpCode.LoadIndirectIntPtr:
                case OpCode.LoadIndirectSingle:
                case OpCode.LoadIndirectDouble:
                case OpCode.LoadIndirect_ref:
                case OpCode.StoreIndirect_ref:
                case OpCode.StoreIndirectInt8:
                case OpCode.StoreIndirectInt16:
                case OpCode.StoreIndirectInt32:
                case OpCode.StoreIndirectInt64:
                case OpCode.StoreIndirectSingle:
                case OpCode.StoreIndirectDouble:
                case OpCode.Add:
                case OpCode.Sub:
                case OpCode.Mul:
                case OpCode.Div:
                case OpCode.Div_un:
                case OpCode.Rem:
                case OpCode.Rem_un:
                case OpCode.And:
                case OpCode.Or:
                case OpCode.Xor:
                case OpCode.Shl:
                case OpCode.Shr:
                case OpCode.Shr_un:
                case OpCode.Neg:
                case OpCode.Not:
                case OpCode.ConvertToInt8:
                case OpCode.ConvertToInt16:
                case OpCode.ConvertToInt32:
                case OpCode.ConvertToInt64:
                case OpCode.ConvertToSingle:
                case OpCode.ConvertToDouble:
                case OpCode.ConvertToUInt32:
                case OpCode.ConvertToUInt64:
                    return FlowType.Next;
                case OpCode.CallVirtual:
                    return FlowType.MethodCall;
                case OpCode.CopyObject:
                case OpCode.LoadObject:
                case OpCode.LoadString:
                    return FlowType.Next;
                case OpCode.Newobj:
                    return FlowType.MethodCall;
                case OpCode.Castclass:
                case OpCode.Isinst:
                case OpCode.Conv_r_un:
                case OpCode.Unbox:
                    return FlowType.Next;
                case OpCode.Throw:
                    return FlowType.Throw;
                case OpCode.LoadField:
                case OpCode.LoadFieldAddress:
                case OpCode.StoreField:
                case OpCode.LoadStaticField:
                case OpCode.LoadStaticFieldAddress:
                case OpCode.StoreStaticField:
                case OpCode.StoreObject:
                case OpCode.ConvertUnsignedOverflowToInt8:
                case OpCode.ConvertUnsignedOverflowToInt16:
                case OpCode.ConvertUnsignedOverflowToInt32:
                case OpCode.ConvertUnsignedOverflowToInt64:
                case OpCode.ConvertUnsignedOverflowToUInt8:
                case OpCode.ConvertUnsignedOverflowToUInt16:
                case OpCode.ConvertUnsignedOverflowToUInt32:
                case OpCode.ConvertUnsignedOverflowToUInt64:
                case OpCode.ConvertUnsignedOverflowToIntPtr:
                case OpCode.ConvertUnsignedOverflowToUIntPtr:
                case OpCode.Box:
                case OpCode.Newarr:
                case OpCode.LoadLength:
                case OpCode.LoadElementAddress:
                case OpCode.LoadElementInt8:
                case OpCode.LoadElementUInt8:
                case OpCode.LoadElementInt16:
                case OpCode.LoadElementUInt16:
                case OpCode.LoadElementInt32:
                case OpCode.LoadElementUInt32:
                case OpCode.LoadElementInt64:
                case OpCode.LoadElementIntPtr:
                case OpCode.LoadElementSingle:
                case OpCode.LoadElementDouble:
                case OpCode.LoadElement_ref:
                case OpCode.StoreElementIntPtr:
                case OpCode.StoreElementInt8:
                case OpCode.StoreElementInt16:
                case OpCode.StoreElementInt32:
                case OpCode.StoreElementInt64:
                case OpCode.StoreElementSingle:
                case OpCode.StoreElementDouble:
                case OpCode.StoreElement_ref:
                case OpCode.LoadElement:
                case OpCode.StoreElement:
                case OpCode.Unbox_any:
                case OpCode.ConvertOverflowToInt8:
                case OpCode.ConvertOverflowToUInt8:
                case OpCode.ConvertOverflowToInt16:
                case OpCode.ConvertOverflowToUInt16:
                case OpCode.ConvertOverflowToInt32:
                case OpCode.ConvertOverflowToUInt32:
                case OpCode.ConvertOverflowToInt64:
                case OpCode.ConvertOverflowToUInt64:
                case OpCode.Refanyval:
                case OpCode.Ckfinite:
                case OpCode.Mkrefany:
                case OpCode.Ldtoken:
                case OpCode.ConvertToUInt16:
                case OpCode.ConvertToUInt8:
                case OpCode.ConvertToIntPtr:
                case OpCode.ConvertOverflowToIntPtr:
                case OpCode.ConvertOverflowToUIntPtr:
                case OpCode.Add_ovf:
                case OpCode.Add_ovf_un:
                case OpCode.Mul_ovf:
                case OpCode.Mul_ovf_un:
                case OpCode.Sub_ovf:
                case OpCode.Sub_ovf_un:
                    return FlowType.Next;
                case OpCode.Endfinally:
                    return FlowType.Next;
                case OpCode.Leave:
                case OpCode.Leave_s:
                    return FlowType.Leave;
                case OpCode.StoreIndirectIntPtr:
                case OpCode.Conv_u:
                case OpCode.Prefix7:
                case OpCode.Prefix6:
                case OpCode.Prefix5:
                case OpCode.Prefix4:
                case OpCode.Prefix3:
                case OpCode.Prefix2:
                case OpCode.Prefix1:
                case OpCode.Prefixref:
                case OpCode.Arglist:
                case OpCode.CompareEq:
                case OpCode.CompareGt:
                case OpCode.CompareUGt:
                case OpCode.CompareLt:
                case OpCode.CompareULt:
                case OpCode.LoadFunction:
                case OpCode.LoadVirtualFunction:
                case OpCode.LoadArgument:
                case OpCode.LoadArgumentAddress:
                case OpCode.StoreArgument:
                case OpCode.LoadLocal:
                case OpCode.LoadLocalAddress:
                case OpCode.StoreLocal:
                case OpCode.Localloc:
                    return FlowType.Next;
                case OpCode.Endfilter:
                    return FlowType.Unsuported;
                case OpCode.Unaligned:
                case OpCode.Volatile:
                    return FlowType.Next;
                case OpCode.Tailcall:
                    return FlowType.Unsuported;;
                case OpCode.Initobj:
                case OpCode.Constrained:
                case OpCode.Cpblk:
                case OpCode.Initblk:
                    return FlowType.Next;
                case OpCode.Rethrow:
                    return FlowType.Throw;
                case OpCode.Sizeof:
                case OpCode.Refanytype:
                case OpCode.Readonly:
                    return FlowType.Next;
            }

            throw new NotSupportedException();
        }

        /// <summary>
        /// Gets the type of the argument.
        /// </summary>
        /// <param name="opCode">The op code.</param>
        /// <returns>Argument type for the opCode.</returns>
        public static OpArgumentType GetArgumentType(OpCode opCode)
        {
            switch (opCode)
            {
                case OpCode.Nop:
                    return OpArgumentType.None;
                case OpCode.Break:
                    return OpArgumentType.BranchTarget;
                case OpCode.LoadArgument_0:
                case OpCode.LoadArgument_1:
                case OpCode.LoadArgument_2:
                case OpCode.LoadArgument_3:
                case OpCode.LoadLocal_0:
                case OpCode.LoadLocal_1:
                case OpCode.LoadLocal_2:
                case OpCode.LoadLocal_3:
                case OpCode.StoreLocal_0:
                case OpCode.StoreLocal_1:
                case OpCode.StoreLocal_2:
                case OpCode.StoreLocal_3:
                    return OpArgumentType.None;
                case OpCode.LoadArgument_s:
                case OpCode.LoadArgumentAddress_s:
                case OpCode.StoreArgument_s:
                case OpCode.LoadLocal_s:
                case OpCode.LoadLocalAddress_s:
                case OpCode.StoreLocal_s:
                    return OpArgumentType.Constant;
                case OpCode.LoadNull:
                case OpCode.LoadConstantInt32_m1:
                case OpCode.LoadConstantInt32_0:
                case OpCode.LoadConstantInt32_1:
                case OpCode.LoadConstantInt32_2:
                case OpCode.LoadConstantInt32_3:
                case OpCode.LoadConstantInt32_4:
                case OpCode.LoadConstantInt32_5:
                case OpCode.LoadConstantInt32_6:
                case OpCode.LoadConstantInt32_7:
                case OpCode.LoadConstantInt32_8:
                    return OpArgumentType.None;
                case OpCode.LoadConstantInt32_s:
                case OpCode.LoadConstantInt32:
                case OpCode.LoadConstantInt64:
                    return OpArgumentType.Constant;
                case OpCode.LoadConstantSingle:
                case OpCode.LoadConstantDouble:
                    return OpArgumentType.ConstantDouble;
                case OpCode.Dup:
                case OpCode.DupCopy:
                case OpCode.Pop:
                case OpCode.CatchEntry:
                    return OpArgumentType.None;
                case OpCode.Jmp:
                case OpCode.Call:
                case OpCode.CallIndirect:
                    return OpArgumentType.Method;
                case OpCode.Return:
                    return OpArgumentType.None;
                case OpCode.Branch_s:
                case OpCode.BranchFalse_s:
                case OpCode.BranchTrue_s:
                case OpCode.BranchEq_s:
                case OpCode.BranchGe_s:
                case OpCode.BranchGt_s:
                case OpCode.BranchLe_s:
                case OpCode.BranchLt_s:
                case OpCode.BranchUNe_s:
                case OpCode.BranchUGe_s:
                case OpCode.BranchUGt_s:
                case OpCode.BranchULe_s:
                case OpCode.BranchULt_s:
                case OpCode.Branch:
                case OpCode.BranchFalse:
                case OpCode.BranchTrue:
                case OpCode.BranchEq:
                case OpCode.BranchGe:
                case OpCode.BranchGt:
                case OpCode.BranchLe:
                case OpCode.BranchLt:
                case OpCode.BranchUNe:
                case OpCode.BranchUGe:
                case OpCode.BranchUGt:
                case OpCode.BranchULe:
                case OpCode.BranchULt:
                    return OpArgumentType.BranchTarget;
                case OpCode.Switch:
                    return OpArgumentType.SwitchTargets;
                case OpCode.LoadIndirectInt8:
                case OpCode.LoadIndirectUInt8:
                case OpCode.LoadIndirectInt16:
                case OpCode.LoadIndirectUInt16:
                case OpCode.LoadIndirectInt32:
                case OpCode.LoadIndirectUInt32:
                case OpCode.LoadIndirectInt64:
                case OpCode.LoadIndirectIntPtr:
                case OpCode.LoadIndirectSingle:
                case OpCode.LoadIndirectDouble:
                case OpCode.LoadIndirect_ref:
                case OpCode.StoreIndirect_ref:
                case OpCode.StoreIndirectInt8:
                case OpCode.StoreIndirectInt16:
                case OpCode.StoreIndirectInt32:
                case OpCode.StoreIndirectInt64:
                case OpCode.StoreIndirectSingle:
                case OpCode.StoreIndirectDouble:
                case OpCode.Add:
                case OpCode.Sub:
                case OpCode.Mul:
                case OpCode.Div:
                case OpCode.Div_un:
                case OpCode.Rem:
                case OpCode.Rem_un:
                case OpCode.And:
                case OpCode.Or:
                case OpCode.Xor:
                case OpCode.Shl:
                case OpCode.Shr:
                case OpCode.Shr_un:
                case OpCode.Neg:
                case OpCode.Not:
                case OpCode.ConvertToInt8:
                case OpCode.ConvertToInt16:
                case OpCode.ConvertToInt32:
                case OpCode.ConvertToInt64:
                case OpCode.ConvertToSingle:
                case OpCode.ConvertToDouble:
                case OpCode.ConvertToUInt32:
                case OpCode.ConvertToUInt64:
                    return OpArgumentType.None;
                case OpCode.CallVirtual:
                    return OpArgumentType.Method;
                case OpCode.CopyObject:
                case OpCode.LoadObject:
                case OpCode.LoadDefaultValue:
                    return OpArgumentType.ObjectType;
                case OpCode.LoadString:
                    return OpArgumentType.ConstantString;
                case OpCode.Newobj:
                    return OpArgumentType.Method;
                case OpCode.Castclass:
                case OpCode.Isinst:
                    return OpArgumentType.ObjectType;
                case OpCode.Conv_r_un:
                    return OpArgumentType.None;
                case OpCode.Unbox:
                    return OpArgumentType.ObjectType;
                case OpCode.Throw:
                    return OpArgumentType.None;
                case OpCode.LoadField:
                case OpCode.LoadFieldAddress:
                case OpCode.StoreField:
                case OpCode.LoadStaticField:
                case OpCode.LoadStaticFieldAddress:
                case OpCode.StoreStaticField:
                    return OpArgumentType.Field;
                case OpCode.StoreObject:
                    return OpArgumentType.ObjectType;
                case OpCode.ConvertUnsignedOverflowToInt8:
                case OpCode.ConvertUnsignedOverflowToInt16:
                case OpCode.ConvertUnsignedOverflowToInt32:
                case OpCode.ConvertUnsignedOverflowToInt64:
                case OpCode.ConvertUnsignedOverflowToUInt8:
                case OpCode.ConvertUnsignedOverflowToUInt16:
                case OpCode.ConvertUnsignedOverflowToUInt32:
                case OpCode.ConvertUnsignedOverflowToUInt64:
                case OpCode.ConvertUnsignedOverflowToIntPtr:
                case OpCode.ConvertUnsignedOverflowToUIntPtr:
                    return OpArgumentType.None;
                case OpCode.Box:
                case OpCode.Newarr:
                    return OpArgumentType.ObjectType;
                case OpCode.LoadLength:
                case OpCode.LoadElementAddress:
                case OpCode.LoadElementInt8:
                case OpCode.LoadElementUInt8:
                case OpCode.LoadElementInt16:
                case OpCode.LoadElementUInt16:
                case OpCode.LoadElementInt32:
                case OpCode.LoadElementUInt32:
                case OpCode.LoadElementInt64:
                case OpCode.LoadElementIntPtr:
                case OpCode.LoadElementSingle:
                case OpCode.LoadElementDouble:
                case OpCode.LoadElement_ref:
                case OpCode.StoreElementIntPtr:
                case OpCode.StoreElementInt8:
                case OpCode.StoreElementInt16:
                case OpCode.StoreElementInt32:
                case OpCode.StoreElementInt64:
                case OpCode.StoreElementSingle:
                case OpCode.StoreElementDouble:
                case OpCode.StoreElement_ref:
                case OpCode.LoadElement:
                case OpCode.StoreElement:
                    return OpArgumentType.None;
                case OpCode.Unbox_any:
                    return OpArgumentType.ObjectType;
                case OpCode.ConvertOverflowToInt8:
                case OpCode.ConvertOverflowToUInt8:
                case OpCode.ConvertOverflowToInt16:
                case OpCode.ConvertOverflowToUInt16:
                case OpCode.ConvertOverflowToInt32:
                case OpCode.ConvertOverflowToUInt32:
                case OpCode.ConvertOverflowToInt64:
                case OpCode.ConvertOverflowToUInt64:
                    return OpArgumentType.None;
                case OpCode.Refanyval:
                    return OpArgumentType.ObjectType;
                case OpCode.Ckfinite:
                    return OpArgumentType.None;
                case OpCode.Mkrefany:
                case OpCode.Ldtoken:
                    return OpArgumentType.Token;
                case OpCode.ConvertToUInt16:
                case OpCode.ConvertToUInt8:
                case OpCode.ConvertToIntPtr:
                case OpCode.ConvertOverflowToIntPtr:
                case OpCode.ConvertOverflowToUIntPtr:
                case OpCode.Add_ovf:
                case OpCode.Add_ovf_un:
                case OpCode.Mul_ovf:
                case OpCode.Mul_ovf_un:
                case OpCode.Sub_ovf:
                case OpCode.Sub_ovf_un:
                case OpCode.Endfinally:
                    return OpArgumentType.None;
                case OpCode.Leave:
                case OpCode.Leave_s:
                    return OpArgumentType.BranchTarget;
                case OpCode.StoreIndirectIntPtr:
                case OpCode.Conv_u:
                case OpCode.Prefix7:
                case OpCode.Prefix6:
                case OpCode.Prefix5:
                case OpCode.Prefix4:
                case OpCode.Prefix3:
                case OpCode.Prefix2:
                case OpCode.Prefix1:
                case OpCode.Prefixref:
                case OpCode.Arglist:
                case OpCode.CompareEq:
                case OpCode.CompareGt:
                case OpCode.CompareUGt:
                case OpCode.CompareLt:
                case OpCode.CompareULt:
                case OpCode.LoadFunction:
                    return OpArgumentType.None;
                case OpCode.LoadVirtualFunction:
                    return OpArgumentType.Method;
                case OpCode.LoadArgument:
                case OpCode.LoadArgumentAddress:
                case OpCode.StoreArgument:
                case OpCode.LoadLocal:
                case OpCode.LoadLocalAddress:
                case OpCode.StoreLocal:
                case OpCode.Localloc:
                case OpCode.Endfilter:
                case OpCode.Unaligned:
                case OpCode.Volatile:
                    return OpArgumentType.None;
                case OpCode.Tailcall:
                    return OpArgumentType.Method;
                case OpCode.Initobj:
                    return OpArgumentType.ObjectType;
                case OpCode.Constrained:
                    return OpArgumentType.ObjectType;
                case OpCode.Cpblk:
                case OpCode.Initblk:
                case OpCode.Rethrow:
                    return OpArgumentType.None;
                case OpCode.Sizeof:
                    return OpArgumentType.ObjectType;
                case OpCode.Refanytype:
                case OpCode.Readonly:
                    return OpArgumentType.None;
            }

            throw new NotSupportedException();
        }

        /// <summary>
        /// Gets the type of the element access.
        /// </summary>
        /// <param name="instruction">The instruction.</param>
        /// <returns>Element access type.</returns>
        public static ElementAccessType GetElementAccessType(IlInstruction instruction)
        {
            OpCode opCode = instruction.OpCode;

            switch (opCode)
            {
                case OpCode.StoreIndirectSingle:
                case OpCode.StoreIndirectDouble:
                case OpCode.StoreIndirect_ref:
                case OpCode.StoreIndirectInt8:
                case OpCode.StoreIndirectInt16:
                case OpCode.StoreIndirectInt32:
                case OpCode.StoreIndirectInt64:
                case OpCode.StoreIndirectIntPtr:
                    return ElementAccessType.SetReferenceArgument;
                case OpCode.LoadIndirectSingle:
                case OpCode.LoadIndirectDouble:
                case OpCode.LoadIndirect_ref:
                case OpCode.LoadIndirectInt8:
                case OpCode.LoadIndirectInt16:
                case OpCode.LoadIndirectInt32:
                case OpCode.LoadIndirectInt64:
                case OpCode.LoadIndirectIntPtr:
                case OpCode.LoadIndirectUInt8:
                case OpCode.LoadIndirectUInt16:
                case OpCode.LoadIndirectUInt32:
                    return ElementAccessType.GetReferenceArgument;
                case OpCode.StoreElement:
                case OpCode.StoreElement_ref:
                case OpCode.StoreElementSingle:
                case OpCode.StoreElementDouble:
                case OpCode.StoreElementInt8:
                case OpCode.StoreElementInt16:
                case OpCode.StoreElementInt32:
                case OpCode.StoreElementInt64:
                case OpCode.StoreElementIntPtr:
                    return ElementAccessType.SetArray;
                case OpCode.LoadElement:
                case OpCode.LoadElement_ref:
                case OpCode.LoadElementSingle:
                case OpCode.LoadElementDouble:
                case OpCode.LoadElementInt8:
                case OpCode.LoadElementInt16:
                case OpCode.LoadElementInt32:
                case OpCode.LoadElementInt64:
                case OpCode.LoadElementIntPtr:
                case OpCode.LoadElementUInt8:
                case OpCode.LoadElementUInt16:
                case OpCode.LoadElementUInt32:
                    return ElementAccessType.GetArray;
                case OpCode.StoreField:
                    return ElementAccessType.SetField;
                case OpCode.LoadField:
                    return ElementAccessType.GetField;
                case OpCode.StoreStaticField:
                    return ElementAccessType.SetStaticField;
                case OpCode.LoadStaticField:
                    return ElementAccessType.GetStaticField;
                case OpCode.CallVirtual:
                case OpCode.Call:
                    {
                        MethodReference methodReference = (MethodReference)instruction.OpCodeArgument;
                        MethodDefinition methodDefinition = methodReference.Resolve();
                        PropertyDefinition propertyDefinition =
                            methodDefinition.GetPropertyDefinition() as PropertyDefinition;

                        if (propertyDefinition != null)
                        {
                            if (propertyDefinition.IsStatic())
                            {
                                return propertyDefinition.SetMethod == methodDefinition
                                    ? ElementAccessType.SetStaticProperty
                                    : ElementAccessType.GetStaticProperty;
                            }

                            return propertyDefinition.SetMethod == methodDefinition
                                ? ElementAccessType.SetProperty
                                : ElementAccessType.GetProperty;
                        }
                    }
                    break;
                case OpCode.StoreLocal:
                    return ElementAccessType.SetLocal;
                case OpCode.LoadLocal:
                    return ElementAccessType.GetLocal;
                case OpCode.StoreArgument:
                    return ElementAccessType.SetArgument;
                case OpCode.LoadArgument:
                    return ElementAccessType.GetArgument;
            }

            return ElementAccessType.None;
        }

        public static OpCode GetOpCode(Code code)
        {
            switch (code)
            {
                case Code.Add:
                    return OpCode.Add;
                case Code.Add_Ovf:
                    return OpCode.Add_ovf;
                case Code.Add_Ovf_Un:
                    return OpCode.Add_ovf_un;
                case Code.And:
                    return OpCode.And;
                case Code.Arglist:
                    return OpCode.Arglist;
                case Code.Beq:
                    return OpCode.BranchEq;
                case Code.Beq_S:
                    return OpCode.BranchEq_s;
                case Code.Bge:
                    return OpCode.BranchGe;
                case Code.Bge_S:
                    return OpCode.BranchGe_s;
                case Code.Bge_Un:
                    return OpCode.BranchUGe;
                case Code.Bge_Un_S:
                    return OpCode.BranchUGe_s;
                case Code.Bgt:
                    return OpCode.BranchGt;
                case Code.Bgt_S:
                    return OpCode.BranchGt_s;
                case Code.Bgt_Un:
                    return OpCode.BranchUGt;
                case Code.Bgt_Un_S:
                    return OpCode.BranchUGt_s;
                case Code.Ble:
                    return OpCode.BranchLe;
                case Code.Ble_S:
                    return OpCode.BranchLe_s;
                case Code.Ble_Un:
                    return OpCode.BranchULe;
                case Code.Ble_Un_S:
                    return OpCode.BranchULe_s;
                case Code.Blt:
                    return OpCode.BranchLt;
                case Code.Blt_S:
                    return OpCode.BranchLt_s;
                case Code.Blt_Un:
                    return OpCode.BranchULt;
                case Code.Blt_Un_S:
                    return OpCode.BranchULt_s;
                case Code.Bne_Un:
                    return OpCode.BranchUNe;
                case Code.Bne_Un_S:
                    return OpCode.BranchUNe_s;
                case Code.Box:
                    return OpCode.Box;
                case Code.Br:
                    return OpCode.Branch;
                case Code.Br_S:
                    return OpCode.Branch_s;
                case Code.Break:
                    return OpCode.Break;
                case Code.Brfalse:
                    return OpCode.BranchFalse;
                case Code.Brfalse_S:
                    return OpCode.BranchFalse_s;
                case Code.Brtrue:
                    return OpCode.BranchTrue;
                case Code.Brtrue_S:
                    return OpCode.BranchTrue_s;
                case Code.Call:
                    return OpCode.Call;
                case Code.Calli:
                    return OpCode.CallIndirect;
                case Code.Callvirt:
                    return OpCode.CallVirtual;
                case Code.Castclass:
                    return OpCode.Castclass;
                case Code.Ceq:
                    return OpCode.CompareEq;
                case Code.Cgt:
                    return OpCode.CompareGt;
                case Code.Cgt_Un:
                    return OpCode.CompareUGt;
                case Code.Ckfinite:
                    return OpCode.Ckfinite;
                case Code.Clt:
                    return OpCode.CompareLt;
                case Code.Clt_Un:
                    return OpCode.CompareULt;
                case Code.Constrained:
                    return OpCode.Constrained;
                case Code.Conv_I:
                    return OpCode.ConvertToIntPtr;
                case Code.Conv_I1:
                    return OpCode.ConvertToInt8;
                case Code.Conv_I2:
                    return OpCode.ConvertToInt16;
                case Code.Conv_I4:
                    return OpCode.ConvertToInt32;
                case Code.Conv_I8:
                    return OpCode.ConvertToInt64;
                case Code.Conv_Ovf_I:
                    return OpCode.ConvertOverflowToIntPtr;
                case Code.Conv_Ovf_I1:
                    return OpCode.ConvertOverflowToInt8;
                case Code.Conv_Ovf_I1_Un:
                    return OpCode.ConvertUnsignedOverflowToInt8;
                case Code.Conv_Ovf_I2:
                    return OpCode.ConvertOverflowToInt16;
                case Code.Conv_Ovf_I2_Un:
                    return OpCode.ConvertUnsignedOverflowToInt16;
                case Code.Conv_Ovf_I4:
                    return OpCode.ConvertOverflowToInt32;
                case Code.Conv_Ovf_I4_Un:
                    return OpCode.ConvertUnsignedOverflowToInt32;
                case Code.Conv_Ovf_I8:
                    return OpCode.ConvertOverflowToInt64;
                case Code.Conv_Ovf_I8_Un:
                    return OpCode.ConvertUnsignedOverflowToInt64;
                case Code.Conv_Ovf_I_Un:
                    return OpCode.ConvertUnsignedOverflowToIntPtr;
                case Code.Conv_Ovf_U:
                    return OpCode.ConvertOverflowToUIntPtr;
                case Code.Conv_Ovf_U1:
                    return OpCode.ConvertOverflowToUInt8;
                case Code.Conv_Ovf_U1_Un:
                    return OpCode.ConvertUnsignedOverflowToUInt8;
                case Code.Conv_Ovf_U2:
                    return OpCode.ConvertOverflowToUInt16;
                case Code.Conv_Ovf_U2_Un:
                    return OpCode.ConvertUnsignedOverflowToUInt16;
                case Code.Conv_Ovf_U4:
                    return OpCode.ConvertOverflowToUInt32;
                case Code.Conv_Ovf_U4_Un:
                    return OpCode.ConvertUnsignedOverflowToUInt32;
                case Code.Conv_Ovf_U8:
                    return OpCode.ConvertOverflowToUInt64;
                case Code.Conv_Ovf_U8_Un:
                    return OpCode.ConvertUnsignedOverflowToUInt64;
                case Code.Conv_Ovf_U_Un:
                    return OpCode.ConvertUnsignedOverflowToUIntPtr;
                case Code.Conv_R4:
                    return OpCode.ConvertToSingle;
                case Code.Conv_R8:
                    return OpCode.ConvertToDouble;
                case Code.Conv_R_Un:
                    return OpCode.Conv_r_un;
                case Code.Conv_U:
                    return OpCode.Conv_u;
                case Code.Conv_U1:
                    return OpCode.ConvertToUInt8;
                case Code.Conv_U2:
                    return OpCode.ConvertToUInt16;
                case Code.Conv_U4:
                    return OpCode.ConvertToUInt32;
                case Code.Conv_U8:
                    return OpCode.ConvertToUInt64;
                case Code.Cpblk:
                    return OpCode.Cpblk;
                case Code.Cpobj:
                    return OpCode.CopyObject;
                case Code.Div:
                    return OpCode.Div;
                case Code.Div_Un:
                    return OpCode.Div_un;
                case Code.Dup:
                    return OpCode.Dup;
                case Code.Endfilter:
                    return OpCode.Endfilter;
                case Code.Endfinally:
                    return OpCode.Endfinally;
                case Code.Initblk:
                    return OpCode.Initblk;
                case Code.Initobj:
                    return OpCode.Initobj;
                case Code.Isinst:
                    return OpCode.Isinst;
                case Code.Jmp:
                    return OpCode.Jmp;
                case Code.Ldarg:
                    return OpCode.LoadArgument;
                case Code.Ldarg_0:
                    return OpCode.LoadArgument_0;
                case Code.Ldarg_1:
                    return OpCode.LoadArgument_1;
                case Code.Ldarg_2:
                    return OpCode.LoadArgument_2;
                case Code.Ldarg_3:
                    return OpCode.LoadArgument_3;
                case Code.Ldarg_S:
                    return OpCode.LoadArgument_s;
                case Code.Ldarga:
                    return OpCode.LoadArgumentAddress;
                case Code.Ldarga_S:
                    return OpCode.LoadArgumentAddress_s;
                case Code.Ldc_I4:
                    return OpCode.LoadConstantInt32;
                case Code.Ldc_I4_0:
                    return OpCode.LoadConstantInt32_0;
                case Code.Ldc_I4_1:
                    return OpCode.LoadConstantInt32_1;
                case Code.Ldc_I4_2:
                    return OpCode.LoadConstantInt32_2;
                case Code.Ldc_I4_3:
                    return OpCode.LoadConstantInt32_3;
                case Code.Ldc_I4_4:
                    return OpCode.LoadConstantInt32_4;
                case Code.Ldc_I4_5:
                    return OpCode.LoadConstantInt32_5;
                case Code.Ldc_I4_6:
                    return OpCode.LoadConstantInt32_6;
                case Code.Ldc_I4_7:
                    return OpCode.LoadConstantInt32_7;
                case Code.Ldc_I4_8:
                    return OpCode.LoadConstantInt32_8;
                case Code.Ldc_I4_M1:
                    return OpCode.LoadConstantInt32_m1;
                case Code.Ldc_I4_S:
                    return OpCode.LoadConstantInt32_s;
                case Code.Ldc_I8:
                    return OpCode.LoadConstantInt64;
                case Code.Ldc_R4:
                    return OpCode.LoadConstantSingle;
                case Code.Ldc_R8:
                    return OpCode.LoadConstantDouble;
                case Code.Ldelem_Any:
                    return OpCode.LoadElement;
                case Code.Ldelem_I:
                    return OpCode.LoadElementIntPtr;
                case Code.Ldelem_I1:
                    return OpCode.LoadElementInt8;
                case Code.Ldelem_I2:
                    return OpCode.LoadElementInt16;
                case Code.Ldelem_I4:
                    return OpCode.LoadElementInt32;
                case Code.Ldelem_I8:
                    return OpCode.LoadElementInt64;
                case Code.Ldelem_R4:
                    return OpCode.LoadElementSingle;
                case Code.Ldelem_R8:
                    return OpCode.LoadElementDouble;
                case Code.Ldelem_Ref:
                    return OpCode.LoadElement_ref;
                case Code.Ldelem_U1:
                    return OpCode.LoadElementUInt8;
                case Code.Ldelem_U2:
                    return OpCode.LoadElementUInt16;
                case Code.Ldelem_U4:
                    return OpCode.LoadElementUInt32;
                case Code.Ldelema:
                    return OpCode.LoadElementAddress;
                case Code.Ldfld:
                    return OpCode.LoadField;
                case Code.Ldflda:
                    return OpCode.LoadFieldAddress;
                case Code.Ldftn:
                    return OpCode.LoadFunction;
                case Code.Ldind_I:
                    return OpCode.LoadIndirectIntPtr;
                case Code.Ldind_I1:
                    return OpCode.LoadIndirectInt8;
                case Code.Ldind_I2:
                    return OpCode.LoadIndirectInt16;
                case Code.Ldind_I4:
                    return OpCode.LoadIndirectInt32;
                case Code.Ldind_I8:
                    return OpCode.LoadIndirectInt64;
                case Code.Ldind_R4:
                    return OpCode.LoadIndirectSingle;
                case Code.Ldind_R8:
                    return OpCode.LoadIndirectDouble;
                case Code.Ldind_Ref:
                    return OpCode.LoadIndirect_ref;
                case Code.Ldind_U1:
                    return OpCode.LoadIndirectUInt8;
                case Code.Ldind_U2:
                    return OpCode.LoadIndirectUInt16;
                case Code.Ldind_U4:
                    return OpCode.LoadIndirectUInt32;
                case Code.Ldlen:
                    return OpCode.LoadLength;
                case Code.Ldloc:
                    return OpCode.LoadLocal;
                case Code.Ldloc_0:
                    return OpCode.LoadLocal_0;
                case Code.Ldloc_1:
                    return OpCode.LoadLocal_1;
                case Code.Ldloc_2:
                    return OpCode.LoadLocal_2;
                case Code.Ldloc_3:
                    return OpCode.LoadLocal_3;
                case Code.Ldloc_S:
                    return OpCode.LoadLocal_s;
                case Code.Ldloca:
                    return OpCode.LoadLocalAddress;
                case Code.Ldloca_S:
                    return OpCode.LoadLocalAddress_s;
                case Code.Ldnull:
                    return OpCode.LoadNull;
                case Code.Ldobj:
                    return OpCode.LoadObject;
                case Code.Ldsfld:
                    return OpCode.LoadStaticField;
                case Code.Ldsflda:
                    return OpCode.LoadStaticFieldAddress;
                case Code.Ldstr:
                    return OpCode.LoadString;
                case Code.Ldtoken:
                    return OpCode.Ldtoken;
                case Code.Ldvirtftn:
                    return OpCode.LoadVirtualFunction;
                case Code.Leave:
                    return OpCode.Leave;
                case Code.Leave_S:
                    return OpCode.Leave_s;
                case Code.Localloc:
                    return OpCode.Localloc;
                case Code.Mkrefany:
                    return OpCode.Mkrefany;
                case Code.Mul:
                    return OpCode.Mul;
                case Code.Mul_Ovf:
                    return OpCode.Mul_ovf;
                case Code.Mul_Ovf_Un:
                    return OpCode.Mul_ovf_un;
                case Code.Neg:
                    return OpCode.Neg;
                case Code.Newarr:
                    return OpCode.Newarr;
                case Code.Newobj:
                    return OpCode.Newobj;
                case Code.No:
                    return OpCode.No;
                case Code.Nop:
                    return OpCode.Nop;
                case Code.Not:
                    return OpCode.Not;
                case Code.Or:
                    return OpCode.Or;
                case Code.Pop:
                    return OpCode.Pop;
                case Code.Readonly:
                    return OpCode.Readonly;
                case Code.Refanytype:
                    return OpCode.Refanytype;
                case Code.Refanyval:
                    return OpCode.Refanyval;
                case Code.Rem:
                    return OpCode.Rem;
                case Code.Rem_Un:
                    return OpCode.Rem_un;
                case Code.Ret:
                    return OpCode.Return;
                case Code.Rethrow:
                    return OpCode.Rethrow;
                case Code.Shl:
                    return OpCode.Shl;
                case Code.Shr:
                    return OpCode.Shr;
                case Code.Shr_Un:
                    return OpCode.Shr_un;
                case Code.Sizeof:
                    return OpCode.Sizeof;
                case Code.Starg:
                    return OpCode.StoreArgument;
                case Code.Starg_S:
                    return OpCode.StoreArgument_s;
                case Code.Stelem_Any:
                    return OpCode.StoreElement;
                case Code.Stelem_I:
                    return OpCode.StoreElementIntPtr;
                case Code.Stelem_I1:
                    return OpCode.StoreElementInt8;
                case Code.Stelem_I2:
                    return OpCode.StoreElementInt16;
                case Code.Stelem_I4:
                    return OpCode.StoreElementInt32;
                case Code.Stelem_I8:
                    return OpCode.StoreElementInt64;
                case Code.Stelem_R4:
                    return OpCode.StoreElementSingle;
                case Code.Stelem_R8:
                    return OpCode.StoreElementDouble;
                case Code.Stelem_Ref:
                    return OpCode.StoreElement_ref;
                case Code.Stfld:
                    return OpCode.StoreField;
                case Code.Stind_I:
                    return OpCode.StoreIndirectIntPtr;
                case Code.Stind_I1:
                    return OpCode.StoreIndirectInt8;
                case Code.Stind_I2:
                    return OpCode.StoreIndirectInt16;
                case Code.Stind_I4:
                    return OpCode.StoreIndirectInt32;
                case Code.Stind_I8:
                    return OpCode.StoreIndirectInt64;
                case Code.Stind_R4:
                    return OpCode.StoreIndirectSingle;
                case Code.Stind_R8:
                    return OpCode.StoreIndirectDouble;
                case Code.Stind_Ref:
                    return OpCode.StoreIndirect_ref;
                case Code.Stloc:
                    return OpCode.StoreLocal;
                case Code.Stloc_0:
                    return OpCode.StoreLocal_0;
                case Code.Stloc_1:
                    return OpCode.StoreLocal_1;
                case Code.Stloc_2:
                    return OpCode.StoreLocal_2;
                case Code.Stloc_3:
                    return OpCode.StoreLocal_3;
                case Code.Stloc_S:
                    return OpCode.StoreLocal_s;
                case Code.Stobj:
                    return OpCode.StoreObject;
                case Code.Stsfld:
                    return OpCode.StoreStaticField;
                case Code.Sub:
                    return OpCode.Sub;
                case Code.Sub_Ovf:
                    return OpCode.Sub_ovf;
                case Code.Sub_Ovf_Un:
                    return OpCode.Sub_ovf_un;
                case Code.Switch:
                    return OpCode.Switch;
                case Code.Tail:
                    return OpCode.Tailcall;
                case Code.Throw:
                    return OpCode.Throw;
                case Code.Unaligned:
                    return OpCode.Unaligned;
                case Code.Unbox:
                    return OpCode.Unbox;
                case Code.Unbox_Any:
                    return OpCode.Unbox_any;
                case Code.Volatile:
                    return OpCode.Volatile;
                case Code.Xor:
                    return OpCode.Xor;
                default:
                    throw new NotSupportedException();
            }
        }
    }
}
