//-----------------------------------------------------------------------
// <copyright file="CSharpArgumentInfo.cs" company="">
//     Copyright (c) . All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace Microsoft.CSharp.RuntimeBinder
{
    using System;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

	/// <summary>Represents information about C# dynamic operations that are specific to particular arguments at a call site. Instances of this class are generated by the C# compiler.</summary>
	public enum CSharpArgumentInfoFlags
	{
		/// <summary>No additional information to represent.</summary>
		None = 0,
		/// <summary>The argument's compile-time type should be considered during binding.</summary>
		UseCompileTimeType = 1,
		/// <summary>The argument is a constant.</summary>
		Constant = 2,
		/// <summary>The argument is a named argument.</summary>
		NamedArgument = 4,
		/// <summary>The argument is passed to a ref parameter.</summary>
		IsRef = 8,
		/// <summary>The argument is passed to an out parameter.</summary>
		IsOut = 16,
		/// <summary>The argument is a <see cref="T:System.Type" /> indicating an actual type name used in source. Used only for target objects in static calls.</summary>
		IsStaticType = 32
	}

	/// <summary>Represents information about C# dynamic operations that are specific to particular arguments at a call site. Instances of this class are generated by the C# compiler.</summary>
	public sealed class CSharpArgumentInfo
	{
		/// <summary>Initializes a new instance of the <see cref="T:Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo" /> class.</summary>
		/// <returns>A new instance of the <see cref="T:Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo" /> class.</returns>
		/// <param name="flags">The flags for the argument.</param>
		/// <param name="name">The name of the argument, if named; otherwise null.</param>
		public extern static CSharpArgumentInfo Create(CSharpArgumentInfoFlags flags, string name);
	}
}
