//-----------------------------------------------------------------------
// <copyright file="CSharpBinderFlags.cs" company="">
//     Copyright (c) . All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace Microsoft.CSharp.RuntimeBinder
{
    using System;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

	/// <summary>Represents information about C# dynamic operations that are not specific to particular arguments at a call site. Instances of this class are generated by the C# compiler.</summary>
	public enum CSharpBinderFlags
	{
		/// <summary>There is no additional information required for this binder.</summary>
		None = 0,
		/// <summary>The evaluation of this binder happens in a checked context.</summary>
		CheckedContext = 1,
		/// <summary>The binder represents an invoke on a simple name.</summary>
		InvokeSimpleName = 2,
		/// <summary>The binder represents an invoke on a specialname.</summary>
		InvokeSpecialName = 4,
		/// <summary>The binder represents a logical AND or logical OR that is part of a conditional logical operator evaluation.</summary>
		BinaryOperationLogical = 8,
		/// <summary>The binder represents an explicit conversion.</summary>
		ConvertExplicit = 16,
		/// <summary>The binder represents an implicit conversion for use in an array creation expression.</summary>
		ConvertArrayIndex = 32,
		/// <summary>The result of any bind is going to be indexed get a set index or get index binder.</summary>
		ResultIndexed = 64,
		/// <summary>The value in this set index or set member comes a compound assignment operator.</summary>
		ValueFromCompoundAssignment = 128,
		/// <summary>The binder is used in a position that does not require a result, and can therefore bind to a void returning method.</summary>
		ResultDiscarded = 256
	}
}
