//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cs2JsC.Template.Compiler {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class DefaultSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DefaultSettings defaultInstance = ((DefaultSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefaultSettings())));
        
        public static DefaultSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Owa.Core.Controls")]
        public string ControlsNS {
            get {
                return ((string)(this["ControlsNS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ctrl")]
        public string ControlsNSAlias {
            get {
                return ((string)(this["ControlsNSAlias"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Owa.Core.Controls.Converters")]
        public string ConvertersNS {
            get {
                return ((string)(this["ConvertersNS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cnvt")]
        public string ConvertersNSAlias {
            get {
                return ((string)(this["ConvertersNSAlias"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>dvm:Owa.Desktop.ViewModels</string>
  <string>ctrl:Owa.Core.Controls</string>
  <string>cnvt:Owa.Core.Controls.Converters</string>
  <string>mvm:Owa.Mobile.ViewModels</string>
  <string>mdl:Owa.Core.Models</string>
  <string>mc:Owa.Mobile.Controls</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection KnownNSAliases {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KnownNSAliases"]));
            }
        }
    }
}
